Repository omegat-org/omegat, pull requests merged in 2022-11, with the labels that each got.

#315 Remove the DRAFT label from the title
  doc_src/en/OmegaTUsersManual_xinclude full.xml
Labels: documentation

#324 Remove messages.xml. It is not used in the DocBook build process.
  doc_src/whc-toc.xsl
Labels: build/release, documentation

#325 Ensure the PDF builds properly
  doc_src/en/App_Glossaries.xml
  doc_src/en/App_Segmentation.xml
  doc_src/en/App_ShortCuts.xml
  doc_src/en/Dialogs_ProjectProperties.xml
  doc_src/en/Introduction.xml
  doc_src/en/OmegaT5_EditorsPanes.xml
  doc_src/en/OmegaT5_Menus.xml
  doc_src/en/OmegaT5_Preferences.xml
  doc_src/en/OmegaT5_WindowsAndDialogs.xml
  doc_src/en/Windows_SourceFilesList.xml
  doc_src/en/Windows_TextReplace.xml
Labels: build/release, documentation

#322 Update documentation for the "--config-file" command line option
  doc_src/en/HowTo_Run.xml
Labels: documentation

#326 fix typo and indent in --config-file documentation
  doc_src/en/HowTo_Run.xml
Labels: documentation

#297 Show glossary comment on context menu candidate
  src/org/omegat/gui/glossary/TransTipsPopup.java
Labels: enhancement

#347 Make UI and manual capitalization consistent.
  doc_src/en/Dialogs_ProjectProperties.xml
  doc_src/en/OmegaT5_Preferences.xml
  doc_src/en/Windows_TextReplace.xml
  doc_src/en/Windows_TextSearch.xml
  doc_src/en/index.xml
  src/org/omegat/Bundle.properties
Labels: documentation

#284 Dictionary: notify when search done but no data
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/dictionaries/DictionariesTextArea.java
  src/org/omegat/util/Preferences.java
Labels: enhancement

#354 Removal of Microsoft Azure Translator MT connector
  Plugins.properties
  doc_src/en/OmegaT5_Preferences.xml
  src/org/omegat/Bundle.properties
  src/org/omegat/core/machinetranslators/MicrosoftTranslatorAzure.java
Labels: bug
