Repository omegat-org/omegat, pull requests merged in 2022-12, with the labels that each got.

#358 PluginUtils, PluginInformation: Allow adding individual plugin attributes for plugins such as description and categories in manifest.mf
  Plugins.properties
  build.gradle
  gradle/utils.gradle
  src/org/omegat/core/data/PluginInformation.java
  src/org/omegat/filters2/master/PluginUtils.java
  test/data/plugin/bundled/MANIFEST.MF
  test/data/plugin/simple/MANIFEST.MF
  test/src/org/omegat/core/data/PluginInformationTest.java
  test/src/svn/PluginsTest.java
Labels: enhancement

#378 Documentation for the x-goto functions
  doc_src/en/App_ShortCuts.xml
  doc_src/en/HowTo_UseTM.xml
  doc_src/en/Menus_GoTo.xml
  doc_src/en/OmegaT5_Preferences.xml
  doc_src/en/OmegaT5_ProjectFolder.xml
  src/org/omegat/Bundle.properties
Labels: enhancement, documentation

#391 docs_devel: Fix and update contribution guide
  docs_devel/docs/03.GitWorkFlows.md
  docs_devel/docs/23.CoreMethods.md
  docs_devel/docs/30.CodingStyles.md
  docs_devel/docs/33.TestAndCoverage.md
  docs_devel/docs/index.md
Labels: documentation

#392 Gradle: add jacoco verification rules
  build.gradle
Labels: build/release
