Repository omegat-org/omegat, pull requests merged in 2023-02, with the labels that each got.

#463 refactor: Removal of Microsoft Translator
  Plugins.properties
  doc_src/en/OmegaT5_Preferences.xml
  src/org/omegat/Bundle.properties
  src/org/omegat/Bundle_be.properties
  src/org/omegat/Bundle_ca.properties
  src/org/omegat/Bundle_co.properties
  src/org/omegat/Bundle_cs.properties
  src/org/omegat/Bundle_cy.properties
  src/org/omegat/Bundle_de.properties
  src/org/omegat/Bundle_el.properties
  src/org/omegat/Bundle_es.properties
  src/org/omegat/Bundle_eu.properties
  src/org/omegat/Bundle_fi.properties
  src/org/omegat/Bundle_fr.properties
  src/org/omegat/Bundle_gl.properties
  src/org/omegat/Bundle_hr.properties
  src/org/omegat/Bundle_hu.properties
  src/org/omegat/Bundle_ia.properties
  src/org/omegat/Bundle_it.properties
  src/org/omegat/Bundle_ja.properties
  src/org/omegat/Bundle_ko.properties
  src/org/omegat/Bundle_mfe.properties
  src/org/omegat/Bundle_nl.properties
  src/org/omegat/Bundle_no.properties
  src/org/omegat/Bundle_pl.properties
  src/org/omegat/Bundle_pt.properties
  src/org/omegat/Bundle_pt_BR.properties
  src/org/omegat/Bundle_ru.properties
  src/org/omegat/Bundle_sc.properties
  src/org/omegat/Bundle_sl.properties
  src/org/omegat/Bundle_sv.properties
  src/org/omegat/Bundle_tk.properties
  src/org/omegat/Bundle_tr.properties
  src/org/omegat/Bundle_uk.properties
  src/org/omegat/Bundle_zh_CN.properties
  src/org/omegat/Bundle_zh_TW.properties
  src/org/omegat/core/machinetranslators/MicrosoftTranslatorAzure.java
Labels: refactoring

#465 docs_devel: relocate editor keys note
  docs_devel/docs/80.EditorKeys.md
  docs_devel/docs/index.md
Labels: documentation

#467 fix: always try to calculate the third TM match score (untokenized)
  src/org/omegat/core/statistics/FindMatches.java
Labels: bug

#474 refactor(mt): introduce BaseCachedTranslate class
  src/org/omegat/core/machinetranslators/AbstractMyMemoryTranslate.java
  src/org/omegat/core/machinetranslators/ApertiumTranslate.java
  src/org/omegat/core/machinetranslators/BaseCachedTranslate.java
  src/org/omegat/core/machinetranslators/BaseTranslate.java
  src/org/omegat/core/machinetranslators/BelazarTranslate.java
  src/org/omegat/core/machinetranslators/DeepLTranslate.java
  src/org/omegat/core/machinetranslators/Google2Translate.java
  src/org/omegat/core/machinetranslators/IBMWatsonTranslate.java
  src/org/omegat/core/machinetranslators/YandexCloudTranslate.java
Labels: refactoring

#491 refactor(filters4): avoid catching NPE
  src/org/omegat/filters4/xml/AbstractXmlFilter.java
  src/org/omegat/filters4/xml/openxml/OpenXmlFilter.java
  src/org/omegat/filters4/xml/xliff/Xliff2Filter.java
Labels: refactoring

#507 Update OmegaT5_Preferences.xml
  doc_src/en/OmegaT5_Preferences.xml
Labels: documentation
