Repository omegat-org/omegat, pull requests merged in 2023-06, with the labels that each got.

#618 chore(gradle): support PKCS#11 signing with HSM
  build.gradle
  local.properties.example
Labels: bug, build/release

#619 fix(xml): serialize without empty list
  docs/index.html
  src/org/omegat/core/segmentation/SRX.java
  src/org/omegat/filters2/master/FilterMaster.java
  src/org/omegat/util/ProjectFileStorage.java
  test/src/org/omegat/filters2/master/FilterMasterTest.java
Labels: bug

#630 FR l10n fix for releases/5.8
  doc_src/fr/App_ApplicationFolder.xml
  doc_src/fr/App_ConfigurationFolder.xml
  doc_src/fr/App_FileFilters.xml
  doc_src/fr/App_Regex.xml
  doc_src/fr/App_ShortCuts.xml
  doc_src/fr/Dialogs_ProjectProperties.xml
  doc_src/fr/HowTo_Install.xml
  doc_src/fr/HowTo_Run.xml
  doc_src/fr/InstantStartGuide.xml
  doc_src/fr/Menus_Project.xml
  doc_src/fr/Menus_Tools.xml
  doc_src/fr/Menus_View.xml
  doc_src/fr/OmegaT_EditorsPanes.xml
  doc_src/fr/OmegaT_Preferences.xml
  doc_src/fr/OmegaT_ProjectFolder.xml
  docs/fr/_wh/search.js
  docs/fr/_wh/wh.js
  docs/fr/chapter.appendices.html
  docs/fr/chapter.dialogs.preferences.html
  docs/fr/chapter.how.to.html
  docs/fr/chapter.instant.start.guide.html
  docs/fr/chapter.menus.html
  docs/fr/chapter.panes.html
  docs/fr/chapter.project.folder.html
  docs/fr/chapter.windows.and.dialogs.html
  docs/fr/index.html
  docs/fr/version_fr.properties
  src/org/omegat/Bundle_fr.properties
Labels: documentation, UI

#628 [BUGS#1181] feat: add support for XDXF article in StarDict
  build.gradle
  src/org/omegat/core/dictionaries/StarDict.java
Labels: enhancement

#632 6.1 FR fix
  doc_src/fr/App_ApplicationFolder.xml
  doc_src/fr/App_ConfigurationFolder.xml
  doc_src/fr/App_FileFilters.xml
  doc_src/fr/App_Regex.xml
  doc_src/fr/App_ShortCuts.xml
  doc_src/fr/Dialogs_ProjectProperties.xml
  doc_src/fr/HowTo_Run.xml
  doc_src/fr/InstantStartGuide.xml
  doc_src/fr/Menus_Project.xml
  doc_src/fr/Menus_Tools.xml
  doc_src/fr/Menus_View.xml
  doc_src/fr/OmegaT_EditorsPanes.xml
  doc_src/fr/OmegaT_Preferences.xml
  doc_src/fr/OmegaT_ProjectFolder.xml
  src/org/omegat/Bundle_fr.properties
Labels: documentation, UI

#634 chore(ci): run integration test before weekly release
  azure-pipelines.yml
  ci/azure-pipelines/integ_test_steps.yml
  test-integration/docker/client/Dockerfile
  test-integration/docker/client/entrypoint.sh
Labels: build/release

#636 fix(linux): suppress illegal reflective access warning
  build.gradle
  release/linux-specific/OmegaT
  src/org/omegat/Main.java
Labels: java17, refactoring

#641 chore(gradle): allow failure of chmod in winJRE(64) task
  build.gradle
Labels: build/release

#648 [6.0] docs(webManual): update index_template.html and version_(ca|de).properties
  doc_src/ca/version_ca.properties
  doc_src/de/version_de.properties
  doc_src/index_template.html
Labels: documentation

#650 [6.0] chore(gradle): javadoc configurations
  build.gradle
Labels: build/release, documentation

#649 Update 90.ReleaseProcedure.md
  docs_devel/docs/90.ReleaseProcedure.md
Labels: build/release

#647 chore(gradle): add task group to some
  build.gradle
Labels: build/release

#642 [RFE#1448] feat: support repository mapping in a local project
  src/org/omegat/gui/main/ProjectUICommands.java
Labels: enhancement

#601 feat: display(Error|Warning)RB show multi-line message
  src/org/omegat/gui/main/MainWindow.java
Labels: enhancement

#651 chore/style: javadoc configurations and reduce warnigns
  build.gradle
  src/org/omegat/core/machinetranslators/MachineTranslators.java
  src/org/omegat/core/search/SearchResultEntry.java
  src/org/omegat/core/statistics/CalcStandardStatistics.java
  src/org/omegat/core/statistics/StatCount.java
  src/org/omegat/core/threads/SearchThread.java
  src/org/omegat/externalfinder/item/ExternalFinderItem.java
  src/org/omegat/filters2/IFilter.java
  src/org/omegat/filters2/IParseCallback.java
  src/org/omegat/filters2/html2/HTMLFilter2.java
  src/org/omegat/filters2/text/bundles/ResourceBundleFilter.java
  src/org/omegat/filters2/text/dokuwiki/DokuWikiFilter.java
  src/org/omegat/filters2/xtagqxp/Xtag.java
  src/org/omegat/filters3/Entry.java
  src/org/omegat/filters3/OutOfTurnTag.java
  src/org/omegat/filters3/xml/XMLEntityText.java
  src/org/omegat/filters3/xml/XMLOutOfTurnTag.java
  src/org/omegat/filters3/xml/XMLReader.java
  src/org/omegat/filters3/xml/XMLText.java
  src/org/omegat/filters3/xml/XMLWriter.java
  src/org/omegat/filters3/xml/helpandmanual/HelpAndManualDialect.java
  src/org/omegat/filters3/xml/helpandmanual/HelpAndManualFilter.java
  src/org/omegat/filters3/xml/openxml/OpenXMLOptions.java
  src/org/omegat/filters3/xml/xliff/XLIFFOptions.java
  src/org/omegat/gui/editor/EditorUtils.java
  src/org/omegat/gui/editor/SegmentBuilder.java
  src/org/omegat/gui/editor/autocompleter/AbstractAutoCompleterView.java
  src/org/omegat/gui/editor/autotext/AutotextTableModel.java
  src/org/omegat/gui/main/ProjectUICommands.java
  src/org/omegat/languagetools/LanguageToolNetworkBridge.java
  src/org/omegat/util/DeNormalize.java
  src/org/omegat/util/InlineTagHandler.java
  src/org/omegat/util/Preferences.java
  src/org/omegat/util/StaticUtils.java
  src/org/omegat/util/TagUtil.java
  src/org/omegat/util/Token.java
  src/org/omegat/util/VarExpansion.java
  src/org/omegat/util/VersionChecker.java
  src/org/omegat/util/gui/StaticUIUtils.java
  src/org/omegat/util/xml/DefaultEntityFilter.java
Labels: build/release, documentation

#652 chore(ci): update jre versions
  azure-pipelines.yml
  ci/azure-pipelines/build_steps.yml
Labels: build/release

#627 [BUGS#1180] Support HiDPI on Linux
  src/org/omegat/core/data/ProjectProperties.java
  src/org/omegat/gui/main/MainWindow.java
  src/org/omegat/gui/preferences/view/FontSelectionController.java
  src/org/omegat/util/FileUtil.java
  src/org/omegat/util/Language.java
  src/org/omegat/util/Platform.java
  src/org/omegat/util/StaticUtils.java
  src/org/omegat/util/gui/FontUtil.java
  src/org/omegat/util/gui/UIScale.java
  test/src/org/omegat/core/data/ProjectPropertiesTest.java
  test/src/org/omegat/util/FileUtilTest.java
Labels: bug, java11

#577 [6.1][BUGS#1168] fix: project loading error on source file system link loop
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/RealProject.java
  src/org/omegat/util/FileUtil.java
Labels: bug

#643 [RFE#1364] feat(preference): Disable restore button when no feature
  src/org/omegat/gui/dialogs/PreferencesDialog.java
  src/org/omegat/gui/preferences/IPreferencesController.java
  src/org/omegat/gui/preferences/PreferencesWindowController.java
  src/org/omegat/gui/preferences/view/PluginsPreferencesController.java
  src/org/omegat/gui/preferences/view/SecureStoreController.java
Labels: enhancement

#569 [6.1][RFE#1169] feat: use Apache MINA SSHD for SVN transport
  src/org/omegat/core/team2/impl/SVNAuthenticationManager.java
  src/org/omegat/core/team2/impl/SVNRemoteRepository2.java
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
Labels: enhancement

#646 [RFE#1159] Load only the latest plugin versions
  release/changes.txt
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/PluginInformation.java
  src/org/omegat/filters2/master/PluginUtils.java
  test/data/plugin/jar/anotherPlugin-0.3.0.jar
  test/data/plugin/jar/anotherPlugin-0.3.1.jar
  test/data/plugin/jar/anotherTestPlugin-0.3.0-SNAPSHOT.jar
  test/data/plugin/jar/testPlugin-1.12-1.44.0-6e59379.jar
  test/data/plugin/jar/testPlugin-1.13-1.45.0.jar
  test/src/org/omegat/filters2/master/PluginUtilsTest.java
Labels: enhancement

#656 [6.1] chore: bundle modules in dist files
  build.gradle
Labels: build/release

#645 [BUGS#1164] Fix reloading TMX after team synchronization
  src/org/omegat/core/data/RealProject.java
Labels: bug
