Repository omegat-org/omegat, pull requests merged in 2023-07, with the labels that each got.

#659 [6.0] docs: remove obsolete warning and cleanup image files
  doc_src/ca/HowTo_TranslateOtherFiles.xml
  doc_src/de/HowTo_TranslateOtherFiles.xml
  doc_src/en/HowTo_TranslateOtherFiles.xml
  doc_src/fr/HowTo_TranslateOtherFiles.xml
  doc_src/ja/HowTo_TranslateOtherFiles.xml
  docs/ca/chapter.how.to.html
  docs/ca/images/defaultOmegaTLayout.png
  docs/ca/images/defaultOmegaTLayout_5.7.png
  docs/ca/images/defaultOmegaTLayout_6.0.png
  docs/de/appendix.dictionaries.html
  docs/de/appendix.glossaries.html
  docs/de/appendix.regexp.html
  docs/de/appendix.shortcut.custom.html
  docs/de/appendix.spellchecker.html
  docs/de/chapter.how.to.html
  docs/de/chapter.installing.and.running.html
  docs/de/howtos.html
  docs/de/images/DictMerriamWebster.png
  docs/de/images/GlossaryEntry_25.png
  docs/de/images/GlossaryPane_25.png
  docs/de/images/MultiTerm_Glossary_25.png
  docs/de/images/RegexTester.png
  docs/de/images/SpellcheckerSetup_25.png
  docs/de/images/SpellcheckingText.png
  docs/de/images/defaultOmegaTLayout.png
  docs/de/images/defaultOmegaTLayout_5.7.png
  docs/de/images/defaultOmegaTLayout_6.0.png
  docs/de/menus.html
  docs/de/panes.html
  docs/de/project.folder.html
  docs/de/windows.and.dialogs.html
  docs/en/ar01.html
  docs/en/chapter.how.to.html
  docs/en/images/defaultOmegaTLayout.png
  docs/en/images/defaultOmegaTLayout_5.7.png
  docs/en/images/defaultOmegaTLayout_6.0.png
  docs/en/images/modifiedOmegaTLayout.png
  docs/fr/chapter.how.to.html
  docs/fr/images/defaultOmegaTLayout_5.7.png
  docs/fr/images/defaultOmegaTLayout_6.0.png
  docs/ja/ar01.html
  docs/ja/chapter.how.to.html
  docs/ja/images/DictMerriamWebster.png
  docs/ja/images/GlossaryEntry_25.png
  docs/ja/images/GlossaryPane_25.png
  docs/ja/images/MultiTerm_Glossary_25.png
  docs/ja/images/RegexTester.png
  docs/ja/images/SpellcheckerSetup_25.png
  docs/ja/images/SpellcheckingText.png
  docs/ja/images/defaultOmegaTLayout.png
  docs/ja/images/defaultOmegaTLayout_5.7.png
  docs/ja/images/defaultOmegaTLayout_6.0.png
Labels: documentation

#658 [5.8] docs: remove obsolete warning and cleanup image files
  doc_src/ca/HowTo_TranslateOtherFiles.xml
  doc_src/de/HowTo_TranslateOtherFiles.xml
  doc_src/en/HowTo_TranslateOtherFiles.xml
  doc_src/fr/HowTo_TranslateOtherFiles.xml
  doc_src/ja/HowTo_TranslateOtherFiles.xml
  docs/ca/chapter.how.to.html
  docs/de/appendix.dictionaries.html
  docs/de/appendix.glossaries.html
  docs/de/appendix.regexp.html
  docs/de/appendix.shortcut.custom.html
  docs/de/appendix.spellchecker.html
  docs/de/chapter.how.to.html
  docs/de/chapter.installing.and.running.html
  docs/de/howtos.html
  docs/de/images/DictMerriamWebster.png
  docs/de/images/GlossaryEntry_25.png
  docs/de/images/GlossaryPane_25.png
  docs/de/images/MultiTerm_Glossary_25.png
  docs/de/images/RegexTester.png
  docs/de/images/SpellcheckerSetup_25.png
  docs/de/images/SpellcheckingText.png
  docs/de/images/defaultOmegaTLayout_5.7.png
  docs/de/images/defaultOmegaTLayout_6.0.png
  docs/de/menus.html
  docs/de/panes.html
  docs/de/project.folder.html
  docs/de/windows.and.dialogs.html
  docs/en/ar01.html
  docs/en/chapter.how.to.html
  docs/en/images/defaultOmegaTLayout_5.7.png
  docs/en/images/defaultOmegaTLayout_6.0.png
  docs/en/images/modifiedOmegaTLayout.png
  docs/fr/chapter.how.to.html
  docs/fr/first_steps.html
  docs/ja/ar01.html
  docs/ja/chapter.how.to.html
  docs/ja/images/DictMerriamWebster.png
  docs/ja/images/GlossaryEntry_25.png
  docs/ja/images/GlossaryPane_25.png
  docs/ja/images/MultiTerm_Glossary_25.png
  docs/ja/images/RegexTester.png
  docs/ja/images/SpellcheckerSetup_25.png
  docs/ja/images/SpellcheckingText.png
  docs/ja/images/defaultOmegaTLayout_5.7.png
  docs/ja/images/defaultOmegaTLayout_6.0.png
Labels: documentation

#668 [6.0] [BUGS#1181] feat: add support for XDXF article in StarDict
  build.gradle
  release/changes.txt
  src/org/omegat/core/dictionaries/StarDict.java
Labels: bug

#665 fix: FiltersCustomizer consistency
  src/org/omegat/filters2/master/FiltersTableModel.java
  src/org/omegat/gui/filters2/FiltersCustomizerController.java
Labels: bug

#670 fix: display the correct content of the Notes in XLIFF
  release/changes.txt
  src/org/omegat/filters4/xml/xliff/AbstractXliffFilter.java
Labels: bug

#663 [6.1][BUGS#1191] fix: jackson custom serializer for ProjectFileStorage
  src/org/omegat/util/ProjectFileStorage.java
  test/data/project/team.project
  test/data/project/teamMapWithExclude.project
  test/data/project/teamWithMap.project
  test/src/org/omegat/util/ProjectFileStorageTest.java
Labels: bug

#672 docs: typo maches -> matches
  doc_src/en/Menus_Options.xml
Labels: documentation

#678 chore(ci): make identical with master
  azure-pipelines.yml
  ci/azure-pipelines/build_steps.yml
  ci/azure-pipelines/publish_weekly.yml
Labels: build/release

#673 typo maches -> matches
  doc_src/en/Menus_Options.xml
Labels: documentation

#674 typo maches -> matches
  doc_src/en/Menus_Options.xml
Labels: documentation

#677 [BUGS#1195] chore: update Windows installer package build and fix executable icon to new
  build.gradle
  docs_devel/docs/93.BuildingInstallerPackage.md
  release/win32-specific/L4j_OMT.xml
  release/win32-specific/OmegaT.exe
  release/win32-specific/OmegaT.iss
Labels: bug, build/release, documentation

#602 [BUGS#1173] fix(team) ask password/passphrase when ssh key
  build.gradle
  release/changes.txt
  src/org/omegat/Bundle.properties
  src/org/omegat/core/team2/gui/PassphraseDialog.java
  src/org/omegat/core/team2/gui/UserPassDialog.java
  src/org/omegat/core/team2/impl/GITCredentialsProvider.java
  src/org/omegat/core/team2/impl/GITRemoteRepository2.java
  src/org/omegat/core/team2/impl/GITUserPassDialog.form
  src/org/omegat/core/team2/impl/SVNAuthenticationManager.java
  src/org/omegat/core/team2/impl/SVNUserPassDialog.form
  src/org/omegat/core/team2/impl/SVNUserPassDialog.java
Labels: bug

#675 [RFE#1695] Select output format for statistics output: JSON, XML or Text
  src/org/omegat/Bundle.properties
  src/org/omegat/Main.java
  src/org/omegat/core/data/RealProject.java
  src/org/omegat/core/statistics/CalcStandardStatistics.java
  src/org/omegat/core/statistics/StatOutputFormat.java
  src/org/omegat/core/statistics/Statistics.java
  src/org/omegat/gui/preferences/view/SaveOptionsController.java
  src/org/omegat/gui/preferences/view/SaveOptionsPanel.java
  src/org/omegat/util/OConsts.java
  src/org/omegat/util/Preferences.java
Labels: enhancement

#679 chore: bump languagetools@6.1
  build.gradle
  release/changes.txt
Labels: enhancement

#687 docs: update contributors' list
  release/contributors.txt
Labels: documentation

#689 update contributor's list
  release/contributors.txt
Labels: documentation

#688 update contributor's list
  release/contributors.txt
Labels: documentation

#699 docs_devel: update Integration-test procedure
  docs_devel/docs/34.IntegrationTest.md
  test-integration/runner.sh
Labels: documentation

#640 [RFE#1703] feat: add API to insert menu item
  release/changes.txt
  src/org/omegat/externalfinder/ExternalFinder.java
  src/org/omegat/gui/main/BaseMainWindowMenu.java
  src/org/omegat/gui/main/IMainMenu.java
  src/org/omegat/util/gui/MenuExtender.java
  src/org/omegat/util/gui/MenuItemPager.java
  test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
  test/fixtures/org/omegat/core/TestCore.java
  test/src/org/omegat/gui/main/MainWindowMenuTest.java
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayController.java
Labels: enhancement

#701 docs: Expand on machine translation explanation (6.0)
  doc_src/en/Menus_Options.xml
  doc_src/en/OmegaT_EditorsPanes.xml
  doc_src/en/OmegaT_Preferences.xml
Labels: documentation

#693 Fix team feature degrade: Revert "[BUGS#1164] Fix reloading TMX after team synchronization (#645)"
  src/org/omegat/core/data/RealProject.java
Labels: bug

#669 [BUGS#558] fix: incorrect display of rtl segments in fuzzy match pane
  release/changes.txt
  src/org/omegat/filters3/xml/XMLTag.java
  src/org/omegat/gui/common/EntryInfoPane.java
  src/org/omegat/gui/editor/AlphabeticalMarkers.java
  src/org/omegat/gui/editor/Document3.java
  src/org/omegat/gui/editor/EditorController.java
  src/org/omegat/gui/editor/SegmentBuilder.java
  src/org/omegat/gui/editor/mark/ProtectedPartsMarker.java
  src/org/omegat/gui/editor/mark/RemoveTagMarker.java
  src/org/omegat/gui/matches/MatchesVarExpansion.java
  src/org/omegat/gui/properties/SegmentPropertiesArea.java
  src/org/omegat/util/BiDiUtils.java
  src/org/omegat/util/Language.java
  test/src/org/omegat/gui/matches/MatchesVarExpansionTest.java
  test/src/org/omegat/util/BiDiUtilsTest.java
Labels: bug

#707 chore(ci/build): fix windows build issues
  azure-pipelines.yml
  build.gradle
  ci/azure-pipelines/build_steps.yml
  ci/azure-pipelines/publish_weekly.yml
Labels: build/release

#698 chore(integ-test): update server entrypoint.sh
  release/changes.txt
  test-integration/docker/server/entrypoint.sh
Labels: bug

#681 chore: linux aarch64 jre bundle
  build.gradle
Labels: build/release

#710 Update phrasing in installation section
  doc_src/en/HowTo_Install.xml
Labels: documentation

#712 [6.0] fix: google2 MT to ignore model property
  release/changes.txt
  src/org/omegat/core/machinetranslators/Google2Translate.java
Labels: bug

#711 [BUGS#1206] fix: google2 MT to ignore model property
  machinetranslators/google/src/main/java/org/omegat/core/machinetranslators/Google2Translate.java
  machinetranslators/google/src/test/java/org/omegat/core/machinetranslators/Google2TranslateTest.java
  release/changes.txt
Labels: bug

#676 [RFE#1690] Have "Commit Target Files" also commit statistics file
  release/changes.txt
  src/org/omegat/core/data/RealProject.java
Labels: enhancement

#706 [BUGS#1204] fix: dependencies `lucene-gosen:5.5.1:ipadic` based on `Lucene/Solr-5.5.5` and `LanguageTool-6.1`
  build.gradle
  machinetranslators/apertium/build.gradle
  machinetranslators/belazar/build.gradle
  machinetranslators/deepl/build.gradle
  machinetranslators/google/build.gradle
  machinetranslators/ibmwatson/build.gradle
  machinetranslators/mymemory/build.gradle
  machinetranslators/yandex/build.gradle
  release/changes.txt
  test/src/org/omegat/languagetools/LuceneGosenCompatibilityTest.java
  tipoftheday/build.gradle
Labels: bug, build/release
