Repository omegat-org/omegat, pull requests merged in 2023-01, with the labels that each got.

#410 Docs_devel: document, L10N, website and scripting
  docs_devel/docs/00.ContributingEcoSystem.md
  docs_devel/docs/01.ContributingOmegaT.md
  docs_devel/docs/40.ContributingDocument.md
  docs_devel/docs/45.LocalizeApplicationAndManuals.md
  docs_devel/docs/47.WebsiteProject.md
  docs_devel/docs/51.HowToWriteScript.md
  docs_devel/docs/81.ExternalFinder.md
  docs_devel/docs/90.ReleaseProcedure.md
  docs_devel/docs/91.appendix.md
  docs_devel/docs/index.md
Labels: documentation

#407 OmegaT.app can be used with open be launched from the command line.
  doc_src/en/HowTo_Run.xml
Labels: documentation

#419 MT: fix method signature change caused not found from plugin
  src/org/omegat/core/machinetranslators/BaseTranslate.java
Labels: bug

#426 Clarify target file filter variable use
  doc_src/en/App_FileFilters.xml
Labels: documentation

#429 aligner: Improve font setting and refactoring
  src/org/omegat/gui/align/AlignPanelController.java
Labels: enhancement

#428 Fix search window field font
  src/org/omegat/gui/search/SearchWindowController.java
Labels: bug

#423 GUI: filter sort order of filter list
  src/org/omegat/gui/filters2/FiltersCustomizerController.java
Labels: enhancement

#425 team: git: suppress debug log for git connections
  src/org/omegat/Bundle.properties
  src/org/omegat/core/team2/impl/GITCredentialsProvider.java
  src/org/omegat/core/team2/impl/JSchCompatLogger.java
Labels: refactoring

#445 Add structure to the file filters section in the Bundle
  src/org/omegat/Bundle.properties
Labels: enhancement
