Repository omegat-org/omegat, pull requests merged in 2023-08, with the labels that each got.

#680 chore(gradle): Mac package distribution with universal launcher and bundle java runtime for both x64 and arm
  build.gradle
  release/mac-specific/OmegaT.app/Contents/Info.plist
  release/mac-specific/OmegaT.app/Contents/MacOS/OmegaT
  release/mac-specific/OmegaT.app/Contents/PkgInfo
  release/mac-specific/OmegaT.app/Contents/Resources/OmegaT.icns
  release/mac-specific/OmegaT.app/Contents/Resources/be.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/cs.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/de.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/fr.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/ia.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/it.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/ja.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/mfe.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/nl.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/no.lproj/Localizable.strings
  release/mac-specific/OmegaT.app/Contents/Resources/pt_BR.lproj/Localizable.strings
Labels: build/release

#718 refactor(test): introduce TestCoreWireMock class
  build.gradle
  machinetranslators/apertium/src/test/java/org/omegat/core/machinetranslators/ApertiumTranslateTest.java
  machinetranslators/deepl/src/test/java/org/omegat/core/machinetranslators/DeepLTranslateTest.java
  machinetranslators/google/src/test/java/org/omegat/core/machinetranslators/Google2TranslateTest.java
  machinetranslators/ibmwatson/src/test/java/org/omegat/core/machinetranslators/IBMWatsonTranslateTest.java
  machinetranslators/mymemory/src/test/java/org/omegat/core/machinetranslators/MyMemoryTranslationTest.java
  test/fixtures/org/omegat/core/TestCore.java
  test/fixtures/org/omegat/core/TestCoreWireMock.java
Labels: refactoring

#721 chore: Update documentation fuzzy match navigation.
  doc_src/en/Menus_Edit.xml
  doc_src/en/OmegaT_EditorsPanes.xml
Labels: documentation

#722 chore(integ-test): support nerdctl and custom logging.propeties
  docs_devel/docs/34.IntegrationTest.md
  src/org/omegat/util/Log.java
  test-integration/docker/client/Dockerfile
  test-integration/docker/client/entrypoint.sh
  test-integration/docker/client/gitconfig
  test-integration/logger.properties
  test-integration/runner.sh
Labels: build/release

#715 [BUGS#1207] fix: catch OOM during auto saving
  release/changes.txt
  src/org/omegat/Bundle.properties
  src/org/omegat/core/threads/SaveThread.java
Labels: bug

#723 chore(integration test): fix custom logging and nerdctl usage
  ci/azure-pipelines/integ_test_steps.yml
  compose.yml
  docker-compose.yml
  docs_devel/docs/34.IntegrationTest.md
  test-integration/docker/client/entrypoint.sh
  test-integration/logger.properties
  test-integration/runner.sh
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
  test-integration/src/org/omegat/util/logging/TestLogFileHandler.java
Labels: refactoring

#622 [6.1] refactor(gui/main): make new UI/Toolbar as an in-source plugin
  Plugins.properties
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/accesstool/AccessTools.java
  src/org/omegat/gui/accesstool/NameAndPathComboBoxRenderer.java
  src/org/omegat/gui/accesstool/ProjectFileInformation.java
  src/org/omegat/gui/accesstool/ProjectFileRenderer.java
  src/org/omegat/gui/accesstool/QuickAccess.java
  src/org/omegat/gui/accesstool/ToolbarComboboxUI.java
  src/org/omegat/gui/main/MainMenuIcons.java
  src/org/omegat/gui/main/MainWindow.java
  src/org/omegat/gui/main/MainWindowBurgerMenu.java
  src/org/omegat/gui/main/MainWindowMenu.java
  src/org/omegat/gui/preferences/IMenuPreferece.java
  src/org/omegat/gui/preferences/MainMenuUI.java
  src/org/omegat/gui/preferences/view/AppearanceController.java
  src/org/omegat/gui/preferences/view/AppearancePreferencesPanel.form
  src/org/omegat/gui/preferences/view/AppearancePreferencesPanel.java
  src/org/omegat/util/Preferences.java
  src/org/omegat/util/gui/UIDesignManager.java
Labels: enhancement, refactoring

#592 [6.2] refactor(tipfotheday): add dialog class
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/OmegaTTipOfTheDayModel.java
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayController.java
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayDialog.java
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayUtils.java
Labels: bug, refactoring

#726 BUG#1213 - Ensure file order consistency between platforms
  src/org/omegat/util/DirectoryMonitor.java
  src/org/omegat/util/FileUtil.java
Labels: bug

#730 [BUGS#1164] Fix properly reloading TMX after team synchronization
  src/org/omegat/core/data/RealProject.java
  src/org/omegat/core/team2/RebaseAndCommit.java
Labels: bug

#732 fix(integration-test): improve docker execution
  test-integration/docker/client/Dockerfile
  test-integration/docker/client/entrypoint.sh
  test-integration/docker/server/entrypoint.sh
Labels: bug
