Repository omegat-org/omegat, pull requests merged in 2023-04, with the labels that each got.

#530 doc(devel): fix typos of release procedure memo
  docs_devel/docs/90.ReleaseProcedure.md
Labels: documentation

#532 Update version number for the documentation
  doc_src/en/manualvariables.mod
  doc_src/en/version.properties
Labels: build/release, documentation

#174 Team: Git: migrate to Apache MINA sshd (RFE#1598)
  build.gradle
  src/org/omegat/Bundle.properties
  src/org/omegat/core/team2/impl/GITCredentialsProvider.java
  src/org/omegat/core/team2/impl/GITRemoteRepository2.java
  test/src/org/omegat/core/team2/impl/GITCredentialsProviderTest.java
Labels: enhancement, java11

#239 [6.1] Use Jackson XML dataformat for JAXB parser and replace TMX, TBX and omegat.prefs loader/saver
  build.gradle
  src/org/omegat/convert/v20to21/Convert20to21.java
  src/org/omegat/core/statistics/StatsResult.java
  src/org/omegat/filters2/master/FilterMaster.java
  src/org/omegat/util/JaxbXmlMapper.java
  src/org/omegat/util/Preferences.java
  src/org/omegat/util/PreferencesXML.java
  src/org/omegat/util/ProjectFileStorage.java
  src/org/omegat/util/TMXReader2.java
  src/org/omegat/util/TMXWriter2.java
  src/org/omegat/util/xml/DefaultEntityFilter.java
  src/org/omegat/util/xml/XMLAttribute.java
  src/org/omegat/util/xml/XMLBlock.java
  src/org/omegat/util/xml/XMLReader.java
  src/org/omegat/util/xml/XMLStreamReader.java
  test/src/org/omegat/filters/XLIFFFilterTest.java
  test/src/org/omegat/util/PreferencesTest.java
  test/src/org/omegat/util/TMXWriterTest.java
  test/src/org/omegat/util/XMLStreamReaderTest.java
Labels: enhancement, java11

#536 docs_devel: fix typos and copyright header around integration test
  docs_devel/docs/34.IntegrationTest.md
  test-integration/docker/client/Dockerfile
  test-integration/docker/server/Dockerfile
Labels: documentation

#245 [Java17] Replace modelToView and viewToModel with modelToView2D and viewToModel2D
  src/org/omegat/gui/dictionaries/DictionariesTextArea.java
  src/org/omegat/gui/editor/EditorController.java
  src/org/omegat/gui/editor/EditorTextArea3.java
  src/org/omegat/gui/editor/autocompleter/AutoCompleter.java
  src/org/omegat/gui/glossary/GlossaryTextArea.java
  src/org/omegat/gui/matches/MatchesTextArea.java
  src/org/omegat/gui/multtrans/MultipleTransPane.java
  src/org/omegat/gui/search/EntryListPane.java
  src/org/omegat/util/Java8Compat.java
  src/org/omegat/util/gui/JTextPaneLinkifier.java
Labels: java17

#458 MT: http json tests, fixes and improves error case behavior
  build.gradle
  src/org/omegat/Bundle.properties
  src/org/omegat/core/machinetranslators/AbstractMyMemoryTranslate.java
  src/org/omegat/core/machinetranslators/ApertiumTranslate.java
  src/org/omegat/core/machinetranslators/DeepLTranslate.java
  src/org/omegat/core/machinetranslators/Google2Translate.java
  src/org/omegat/core/machinetranslators/IBMWatsonTranslate.java
  src/org/omegat/core/machinetranslators/MyMemoryHumanTranslate.java
  src/org/omegat/core/machinetranslators/MyMemoryMachineTranslate.java
  src/org/omegat/core/machinetranslators/YandexCloudTranslate.java
  src/org/omegat/gui/exttrans/MachineTranslateTextArea.java
  test/src/org/omegat/core/machinetranslators/ApertiumTranslateTest.java
  test/src/org/omegat/core/machinetranslators/DeepLTranslateTest.java
  test/src/org/omegat/core/machinetranslators/Google2TranslateTest.java
  test/src/org/omegat/core/machinetranslators/IBMWatsonTranslateTest.java
  test/src/org/omegat/core/machinetranslators/MyMemoryTranslationTest.java
  test/src/org/omegat/core/machinetranslators/TestMachineTranslatorBase.java
  test/src/org/omegat/core/machinetranslators/YandexCloudTranslateTest.java
Labels: bug, build/release, refactoring

#290 [java17] Add nashorn javascript engine
  build.gradle
  lib/licenses/Licenses.txt
Labels: java17, build/release

#539 Enhance/Fix bug: SRX reader/writer, support buggy CONF file to migrate correct SRX file
  build.gradle
  src/org/omegat/Bundle.properties
  src/org/omegat/core/segmentation/LanguageCodes.java
  src/org/omegat/core/segmentation/MapRule.java
  src/org/omegat/core/segmentation/Rule.java
  src/org/omegat/core/segmentation/SRX.java
  src/org/omegat/core/segmentation/datamodels/MappingRulesModel.java
  src/org/omegat/gui/segmentation/SegmentationCustomizerController.java
  test/src/org/omegat/core/segmentation/SRXTest.java
Labels: bug, enhancement

#253 Gradle: use LanguageTools@5.7 and Lucene@5.5.5
  build.gradle
  src/org/omegat/core/machinetranslators/MyMemoryMachineTranslate.java
  src/org/omegat/core/spellchecker/SpellChecker.java
  src/org/omegat/core/spellchecker/SpellCheckerLangToolHunspell.java
  src/org/omegat/core/team2/RebaseAndCommit.java
  src/org/omegat/gui/editor/mark/ProtectedPartsMarker.java
  src/org/omegat/gui/main/ProjectUICommands.java
  src/org/omegat/gui/preferences/view/LanguageToolConfigurationController.java
  src/org/omegat/gui/properties/SegmentPropertiesArea.java
  src/org/omegat/languagetools/LanguageToolNativeBridge.java
  src/org/omegat/tokenizer/BaseTokenizer.java
  src/org/omegat/util/ProjectFileStorage.java
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
  test/src/org/omegat/languagetools/LanguageToolTest.java
  test/src/org/omegat/tokenizer/TokenizerTest.java
Labels: enhancement, build/release

#473 Refactor(MT): handle maxTextLength in BaseTranslate
  src/org/omegat/core/machinetranslators/ApertiumTranslate.java
  src/org/omegat/core/machinetranslators/BaseCachedTranslate.java
  src/org/omegat/core/machinetranslators/BaseTranslate.java
  src/org/omegat/core/machinetranslators/BelazarTranslate.java
  src/org/omegat/core/machinetranslators/DeepLTranslate.java
  src/org/omegat/core/machinetranslators/Google2Translate.java
  src/org/omegat/core/machinetranslators/IBMWatsonTranslate.java
  src/org/omegat/core/machinetranslators/MyMemoryHumanTranslate.java
  src/org/omegat/core/machinetranslators/MyMemoryMachineTranslate.java
  src/org/omegat/core/machinetranslators/YandexCloudTranslate.java
  src/org/omegat/gui/exttrans/IMachineTranslation.java
Labels: refactoring

#541 docs: update japanese manuals and bundles
  doc_src/ja/App_FileFilters.xml
  doc_src/ja/App_Regex.xml
  doc_src/ja/HowTo_Install.xml
  doc_src/ja/HowTo_Run.xml
  doc_src/ja/HowTo_UseTM.xml
  doc_src/ja/HowTo_UseTeamProject.xml
  doc_src/ja/Introduction.xml
  doc_src/ja/Menus_Project.xml
  doc_src/ja/OmegaTUsersManual_xinclude full.xml
  doc_src/ja/OmegaT_Appendices.xml
  doc_src/ja/OmegaT_EditorsPanes.xml
  doc_src/ja/OmegaT_HowTo.xml
  doc_src/ja/OmegaT_Menus.xml
  doc_src/ja/OmegaT_Preferences.xml
  doc_src/ja/OmegaT_ProjectFolder.xml
  doc_src/ja/OmegaT_WindowsAndDialogs.xml
  doc_src/ja/Windows_Aligner.xml
  doc_src/ja/Windows_SourceFilesList.xml
  doc_src/ja/Windows_TextSearch.xml
  doc_src/ja/manualvariables.mod
  doc_src/ja/manualvariables6.mod
  doc_src/ja/version_ja.properties
  docs/ja/_wh/search.js
  docs/ja/_wh/wh.js
  docs/ja/chapter.appendices.html
  docs/ja/chapter.dialogs.preferences.html
  docs/ja/chapter.how.to.html
  docs/ja/chapter.instant.start.guide.html
  docs/ja/chapter.menus.html
  docs/ja/chapter.panes.html
  docs/ja/chapter.project.folder.html
  docs/ja/chapter.windows.and.dialogs.html
  docs/ja/first_steps.html
  docs/ja/index.html
  docs/ja/version_ja.properties
  src/org/omegat/Bundle_ja.properties
Labels: documentation, L10N/Translation

#523 [6.1] newUI
  lib/licenses/Licenses.txt
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/main/BaseMainWindowMenu.java
  src/org/omegat/gui/main/MainMenuIcons.java
  src/org/omegat/gui/main/MainWindow.java
  src/org/omegat/gui/main/MainWindowAccessTools.java
  src/org/omegat/gui/main/MainWindowBurgerMenu.java
  src/org/omegat/gui/main/MainWindowMenu.java
  src/org/omegat/gui/preferences/view/AppearanceController.java
  src/org/omegat/gui/preferences/view/AppearancePreferencesPanel.form
  src/org/omegat/gui/preferences/view/AppearancePreferencesPanel.java
  src/org/omegat/gui/resources/newUI.burgerMenu.png
  src/org/omegat/gui/resources/newUI.burgerMenu.svg
  src/org/omegat/gui/resources/newUI.burgerMenu@2x.png
  src/org/omegat/gui/resources/newUI.dark.burgerMenu.png
  src/org/omegat/gui/resources/newUI.dark.burgerMenu@2x.png
  src/org/omegat/gui/resources/newUI.dark.search.png
  src/org/omegat/gui/resources/newUI.dark.search@2x.png
  src/org/omegat/gui/resources/newUI.dark.settings.png
  src/org/omegat/gui/resources/newUI.dark.settings@2x.png
  src/org/omegat/gui/resources/newUI.search.png
  src/org/omegat/gui/resources/newUI.search.svg
  src/org/omegat/gui/resources/newUI.search@2x.png
  src/org/omegat/gui/resources/newUI.settings.png
  src/org/omegat/gui/resources/newUI.settings@2x.png
  src/org/omegat/gui/theme/DefaultFlatTheme.java
  src/org/omegat/util/Preferences.java
  src/org/omegat/util/StaticUtils.java
  src/org/omegat/util/gui/UIDesignManager.java
  test/src/org/omegat/gui/main/MainWindowMenuTest.java
Labels: enhancement, java11, UI

#543 Update console mode information, and minor related tweaks
  doc_src/OmegaT_new.css
  doc_src/en/HowTo_Run.xml
  src/org/omegat/Bundle.properties
Labels: documentation, UI

#544 docs(tips): fix shortcut key assign
  tipoftheday/docs/tips/en/shortcut_note.html
  tipoftheday/docs/tips/ja/shortcut_note.html
Labels: documentation

#545 newUI: show number of entries in Source File ComboBox
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/main/MainWindowAccessTools.java
Labels: enhancement

#528 chore: add azure-pipelines CI/CD configuration
  azure-pipelines.yml
  build.gradle
  ci/azure-pipelines/check_steps.yml
  ci/azure-pipelines/jre_prep.yml
  ci/azure-pipelines/release_steps.yml
  ci/iscc
  ci/osslsigncode
  ci/readme.txt
  release/ci/authors.txt
  release/ci/build-svn-core.sh
  release/ci/readme.txt
  release/ci/sourceforge-svn-git-sync.sh
Labels: build/release

#542 [releases/6.0] update japanese manuals
  doc_src/ja/App_FileFilters.xml
  doc_src/ja/App_Regex.xml
  doc_src/ja/HowTo_Install.xml
  doc_src/ja/HowTo_Run.xml
  doc_src/ja/HowTo_UseTM.xml
  doc_src/ja/HowTo_UseTeamProject.xml
  doc_src/ja/Introduction.xml
  doc_src/ja/Menus_Project.xml
  doc_src/ja/OmegaTUsersManual_xinclude full.xml
  doc_src/ja/OmegaT_Appendices.xml
  doc_src/ja/OmegaT_EditorsPanes.xml
  doc_src/ja/OmegaT_HowTo.xml
  doc_src/ja/OmegaT_Menus.xml
  doc_src/ja/OmegaT_Preferences.xml
  doc_src/ja/OmegaT_ProjectFolder.xml
  doc_src/ja/OmegaT_WindowsAndDialogs.xml
  doc_src/ja/Windows_Aligner.xml
  doc_src/ja/Windows_SourceFilesList.xml
  doc_src/ja/Windows_TextSearch.xml
  doc_src/ja/manualvariables.mod
  doc_src/ja/manualvariables6.mod
  doc_src/ja/version_ja.properties
  docs/ja/_wh/search.js
  docs/ja/_wh/wh.js
  docs/ja/chapter.appendices.html
  docs/ja/chapter.dialogs.preferences.html
  docs/ja/chapter.how.to.html
  docs/ja/chapter.instant.start.guide.html
  docs/ja/chapter.menus.html
  docs/ja/chapter.panes.html
  docs/ja/chapter.project.folder.html
  docs/ja/chapter.windows.and.dialogs.html
  docs/ja/first_steps.html
  docs/ja/index.html
  docs/ja/version_ja.properties
Labels: documentation, L10N/Translation

#535 [backport 6.0] Improve handling of backup file of omegat.project
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/main/ProjectUICommands.java
  src/org/omegat/util/FileUtil.java
Labels: bug

#534 [backport 5.8] Improve handling of backup file of omegat.project
  doc_src/en/HowTo_UseTM.xml
  docs/en/_wh/search.js
  docs/en/_wh/wh.js
  docs/en/chapter.how.to.html
  docs/en/chapter.instant.start.guide.html
  docs/en/chapter.menus.html
  docs/en/chapter.project.folder.html
  docs/en/chapter.windows.and.dialogs.html
  docs/en/index.html
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/main/ProjectUICommands.java
  src/org/omegat/util/FileUtil.java
Labels: bug

#554 Allow DTD parsing in order to load internal entities
  release/changes.txt
  src/org/omegat/util/JaxbXmlMapper.java
  test/data/project/entities.project
  test/src/org/omegat/util/ProjectFileStorageTest.java
Labels: bug

#555 Check that a segmentation rule has beforeBreak/afterBreak attributes
  src/org/omegat/core/segmentation/Rule.java
Labels: bug

#556 fix: drop xml-apis dependency
  build.gradle
  tipoftheday/build.gradle
Labels: bug

#550 docs_devel: update release procedure and code signing details
  docs_devel/docs/02.HowToBuild.md
  docs_devel/docs/05.Versioning.md
  docs_devel/docs/90.ReleaseProcedure.md
  docs_devel/docs/92.CodeSigning.md
  docs_devel/docs/index.md
Labels: documentation

#546 [CI, 6.0] chore(azure-pipelines): backport ci configurations from master
  azure-pipelines.yml
  build.gradle
  ci/azure-pipelines/check_steps.yml
  ci/azure-pipelines/release_steps.yml
  ci/iscc
  ci/osslsigncode
  ci/readme.txt
  release/authors.txt
  release/ci/build-svn-core.sh
  release/ci/readme.txt
  release/ci/sourceforge-svn-git-sync.sh
Labels: build/release

#548 docs(first step): remove version string from First_Step
  doc_src/ca/First_Steps.xml
  doc_src/en/First_Steps.xml
  doc_src/ja/First_Steps.xml
  docs/ca/first_steps.html
  docs/en/first_steps.html
  docs/ja/first_steps.html
Labels: bug, documentation
