Repository omegat-org/omegat, pull requests merged in 2023-05, with the labels that each got.

#552 feat: detect XMLStreamException
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/RealProject.java
  src/org/omegat/core/statistics/Statistics.java
  src/org/omegat/util/TMXReader2.java
Labels: enhancement

#567 chore(ci): publish weekly and release
  azure-pipelines.yml
  build.gradle
  ci/azure-pipelines/build_steps.yml
  ci/azure-pipelines/publish_release.yml
  ci/azure-pipelines/publish_weekly.yml
Labels: build/release

#563 chore(gradle): code signing *.dylib
  build.gradle
Labels: bug, build/release

#448 Security: filters3: protect XXE parser attack in default parser config
  src/org/omegat/Bundle.properties
  src/org/omegat/filters3/xml/XMLFilter.java
  src/org/omegat/filters3/xml/docbook/DocBookFilter.java
Labels: enhancement

#572 Documentation fixes
  doc_src/en/App_Segmentation.xml
  doc_src/en/App_ShortCuts.xml
  doc_src/en/HowTo_Run.xml
  doc_src/en/HowTo_UseTeamProject.xml
  doc_src/en/Menus_GoTo.xml
Labels: documentation

#566 Digits and letters
  doc_src/en/App_Regex.xml
Labels: documentation

#565 Added an "s" to "these option"
  doc_src/en/App_FileFilters.xml
Labels: documentation

#573 docs(6.0): backport docs updates202305
  doc_src/en/App_FileFilters.xml
  doc_src/en/App_Regex.xml
  doc_src/en/App_Segmentation.xml
  doc_src/en/App_ShortCuts.xml
  doc_src/en/HowTo_Run.xml
  doc_src/en/HowTo_UseTeamProject.xml
  doc_src/en/Menus_GoTo.xml
Labels: documentation

#568 [Java17] refactor unused classes
  build.gradle
  src/org/omegat/gui/dialogs/AboutDialog.java
  src/org/omegat/util/MemoryUtils.java
  src/org/omegat/util/TMXWriter.java
  src/org/omegat/util/xml/DefaultEntityFilter.java
  src/org/omegat/util/xml/XMLAttribute.java
  src/org/omegat/util/xml/XMLBlock.java
  src/org/omegat/util/xml/XMLReader.java
  src/org/omegat/util/xml/XMLStreamReader.java
  test/src/org/omegat/util/XMLStreamReaderTest.java
Labels: java17, refactoring

#560 refactor: improve LanguageToolTest
  build.gradle
  test/src/org/omegat/languagetools/LanguageToolTest.java
Labels: refactoring

#576 fix: avoid using filter option with `null` name
  src/org/omegat/filters2/master/FilterMaster.java
  test/src/org/omegat/filters2/FilterMasterTest.java
Labels: bug

#579 [BUGS#1169] fix: supress useless warnings
  src/org/omegat/logger.properties
Labels: bug

#585 Discrepancies between 5.8 UI and manual + review
  doc_src/en/App_PostProcessingCommands.xml
  doc_src/en/App_Regex.xml
  doc_src/en/App_Segmentation.xml
  doc_src/en/App_ShortCuts.xml
  doc_src/en/HowTo_Run.xml
  doc_src/en/HowTo_UseTM.xml
  doc_src/en/Menus_Edit.xml
  doc_src/en/Menus_View.xml
  doc_src/en/OmegaTUsersManual_xinclude full.xml
  release/contributors.txt
  release/readme.txt
  src/org/omegat/Bundle.properties
Labels: documentation, UI

#584 Discrepancies between 6.0 UI and manual + review
  doc_src/en/App_PostProcessingCommands.xml
  doc_src/en/App_Regex.xml
  doc_src/en/App_Segmentation.xml
  doc_src/en/App_ShortCuts.xml
  doc_src/en/HowTo_Run.xml
  doc_src/en/HowTo_UseTM.xml
  doc_src/en/Menus_Edit.xml
  doc_src/en/Menus_View.xml
  doc_src/en/OmegaTUsersManual_xinclude full.xml
  release/contributors.txt
  release/readme.txt
  src/org/omegat/Bundle.properties
Labels: documentation, UI

#583 Discrepancies between UI and manual + UI review
  doc_src/en/App_PostProcessingCommands.xml
  doc_src/en/App_Regex.xml
  doc_src/en/App_Segmentation.xml
  doc_src/en/App_ShortCuts.xml
  doc_src/en/HowTo_Run.xml
  doc_src/en/HowTo_UseTM.xml
  doc_src/en/Menus_Edit.xml
  doc_src/en/Menus_View.xml
  doc_src/en/OmegaTUsersManual_xinclude full.xml
  release/contributors.txt
  release/readme.txt
  src/org/omegat/Bundle.properties
Labels: documentation, UI

#588 chore: prepare for release 5.8.0
  release/changes.txt
  src/org/omegat/Version.properties
Labels: build/release

#586 chore: allow UTF-8 character as source file
  build.gradle
  test/src/svn/BundleTest.java
Labels: build/release

#599 [6.0] chore: bump target java to 11
  build.gradle
Labels: build/release

#574 [6.1] fix NPE when team project with glossary outside
  src/org/omegat/core/data/RealProject.java
Labels: bug

#589 [6.0] [BUGS#1168] feat:error message for loop link
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/RealProject.java
Labels: bug

#578 [6.1]fix: dependency inconsistency in lucene-gosen
  build.gradle
Labels: bug

#603 chore(ci): update package build script
  azure-pipelines.yml
  build.gradle
  ci/azure-pipelines/build_steps.yml
Labels: build/release

#605 chore: tweak winJRE/winJRE64 builder
  azure-pipelines.yml
  build.gradle
  ci/azure-pipelines/build_steps.yml
  ci/azure-pipelines/publish_release.yml
  ci/azure-pipelines/publish_weekly.yml
  ci/buildiscon.sh
  ci/iscc
Labels: build/release

#606 chore(gradle): Reduce explicit exec for iscc
  build.gradle
  ci/buildiscon.sh
  ci/iscc
Labels: build/release

#609 Fire the `COMPILE` project event before committing target files to repository
  src/org/omegat/core/data/RealProject.java
Labels: bug

#610 [6.1] fix: jackson jaxb parser break SuperTMXMerge library behavior(successor of #587)
  build.gradle
  src/org/omegat/core/segmentation/SRX.java
  src/org/omegat/filters2/master/FilterMaster.java
  src/org/omegat/util/JaxbXmlMapper.java
  src/org/omegat/util/PreferencesXML.java
  src/org/omegat/util/ProjectFileStorage.java
  test/src/org/omegat/filters2/master/FilterMasterTest.java
Labels: bug

#580 [6.1]chore(gradle): set duplicationStrategy for Zip task, and replace deprecated jar.archiveName property
  build.gradle
Labels: build/release

#600 [5.8][BUGS#1168] feat: error message for loop link
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/RealProject.java
Labels: bug

#608 chore: Realign with l10n and fix typo
  doc_src/en/App_ShortCuts.xml
  src/org/omegat/Bundle.properties
Labels: build/release, UI

#598 [6.1] feat/style: check malformed character in java source
  docs_devel/docs/30.CodingStyles.md
  src/org/omegat/core/team2/impl/GITExternalGpgSigner.java
  src/org/omegat/gui/editor/SegmentBuilder.java
  src/org/omegat/gui/exttrans/IMTGlossarySupplier.java
  src/org/omegat/gui/notes/NotesTextArea.java
  src/org/omegat/gui/preferences/view/EditingBehaviorPanel.java
  src/org/omegat/tokenizer/LuceneGermanTokenizer.java
  src/org/omegat/util/Preferences.java
  test/src/org/omegat/core/statistics/FindMatchesTest.java
  test/src/org/omegat/core/team2/SVNRemoteRepository2IT.java
  test/src/org/omegat/util/HTMLUtilsTest.java
  test/src/svn/BundleTest.java
Labels: build/release, documentation

#615 fix(git): Grab hostkey fingerprint message from apache sshd
  src/org/omegat/core/team2/impl/GITCredentialsProvider.java
Labels: bug

#617 chore(ci): no use of artifact upload
  ci/azure-pipelines/build_steps.yml
  ci/azure-pipelines/check_steps.yml
  ci/azure-pipelines/publish_release.yml
  ci/azure-pipelines/publish_weekly.yml
Labels: build/release

#620 fix(util): fix always to return GMT lastModifiedDate string
  src/org/omegat/util/FileUtil.java
Labels: bug

#626 (final) align 6.0 and 5.8 bundle
  src/org/omegat/Bundle.properties
Labels: UI
