Repository omegat-org/omegat, pull requests merged in 2024-01, with the labels that each got.

#903 [BUGS#1240]chore: windows: search JRE in PATH
  build.gradle
Labels: build/release

#901 [6.0][BUGS#1195,BUGS#1240] chore: update windows launcher executable generation
  build.gradle
  release/changes.txt
  release/win32-specific/L4j_OMT.xml
  release/win32-specific/OmegaT.exe
  release/win32-specific/OmegaT.iss
Labels: bug, build/release

#907 fix: docker/nerdctl detection
  ci/iscc
  ci/osslsigncode
  doc_src/docgen
Labels: build/release

#902 [6.0][BUGS#1166]fix: write the project properties in the backup instead of copying file
  release/changes.txt
  src/org/omegat/gui/main/ProjectUICommands.java
  src/org/omegat/util/FileUtil.java
  src/org/omegat/util/ProjectFileStorage.java
Labels: bug

#911 style: aligner files
  aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java
  aligner/src/main/java/org/omegat/gui/align/AlignPanelController.java
  aligner/src/main/java/org/omegat/gui/align/SplittingPanelController.java
  config/checkstyle/suppressions.xml
Labels: refactoring

#912 style: machinetranslators files
  machinetranslators/google/src/main/java/org/omegat/machinetranslators/google/Google2Translate.java
  machinetranslators/ibmwatson/src/main/java/org/omegat/machinetranslators/ibmwatson/IBMWatsonTranslate.java
Labels: refactoring

#916 refactor: initialize SVNKit preference in constructor
  src/org/omegat/core/team2/impl/SVNRemoteRepository2.java
Labels: refactoring

#915 refactor: UIDesignManager.initialize
  src/org/omegat/Main.java
  src/org/omegat/core/Core.java
  src/org/omegat/util/gui/UIDesignManager.java
Labels: refactoring

#917 refactor/test: initialize remote repository plugins before creating local repository
  test/src/org/omegat/core/team2/AbstractRemoteRepository2IT.java
Labels: refactoring

#918 refactor: keep Core.initializeGUI() as deprecated
  src/org/omegat/core/Core.java
Labels: refactoring

#921 chore: bump guava@32.1.2-jre
  build.gradle
  gradle/libs.versions.toml
Labels: dependencies

#920 chore: resolve conflict in annotations jar
  build.gradle
Labels: dependencies

#914 [6.0] backport doc build container command
  build.gradle
  ci/iscc
  doc_src/docgen
Labels: build/release

#924 [BUGS#1242] fix Preferences>SaveOptionsPanel - UI of user level post-translate command
  release/changes.txt
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/preferences/view/SaveOptionsPanel.form
  src/org/omegat/gui/preferences/view/SaveOptionsPanel.java
Labels: bug

#925 docs: fix pdf generation and restructure manual generations
  build.gradle
  doc_src/build.xml
  doc_src/docgen
  doc_src/en/OmegaT_EditorsPanes.xml
  doc_src/ja/OmegaT_EditorsPanes.xml
Labels: bug, documentation

#929 chore: bump rstaui version
  gradle/libs.versions.toml
Labels: dependencies, java

#883 [BUGS#1233] fix: Give a proper feedback when filter got character encoding error
  src/org/omegat/Bundle.properties
  src/org/omegat/filters2/master/FilterMaster.java
Labels: bug

#932 [BUGS#1243] fix: restartGUI when jpackage distribution
  src/org/omegat/Bundle.properties
  src/org/omegat/Main.java
Labels: bug, linux

#933 Correct SDLXLIFF comments
  src/org/omegat/filters4/xml/xliff/SdlXliff.java
Labels: bug
