Repository omegat-org/omegat, pull requests merged in 2024-12, with the labels that each got.

#1203 refactor: BaseMainWindowMenu#createMenu to accept component name
  src/org/omegat/gui/main/BaseMainWindowMenu.java
Labels: refactoring

#1210 chore: test acceptance: stabilize flaky aligner acceptance test
  build.gradle
  test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
Labels: build/release

#1175 feat: EditorUtils use document's locale to splitting words
  build.gradle
  gradle/libs.versions.toml
  language-modules/ja/build.gradle
  src/org/omegat/gui/editor/EditorController.java
  src/org/omegat/gui/editor/EditorTextArea3.java
  src/org/omegat/gui/editor/EditorUtils.java
  test-acceptance/data/project_CN_JP/.gitignore
  test-acceptance/data/project_CN_JP/dictionary/.keep
  test-acceptance/data/project_CN_JP/glossary/glossary.txt
  test-acceptance/data/project_CN_JP/omegat.project
  test-acceptance/data/project_CN_JP/omegat/ignored_words.txt
  test-acceptance/data/project_CN_JP/omegat/last_entry.properties
  test-acceptance/data/project_CN_JP/omegat/learned_words.txt
  test-acceptance/data/project_CN_JP/omegat/project_save.tmx
  test-acceptance/data/project_CN_JP/source/source.txt
  test-acceptance/data/project_CN_JP/target/.keep
  test-acceptance/data/project_CN_JP/tm/.keep
  test-acceptance/src/org/omegat/gui/editor/EditorUtilsTest.java
  test/src/org/omegat/gui/editor/EditorUtilsTest.java
  tipoftheday/build.gradle
Labels: enhancement

#1212 chore: fix error on Integration Test
  src/org/omegat/core/team2/impl/GITCredentialsProvider.java
  src/org/omegat/core/team2/impl/SVNAuthenticationManager.java
  test-integration/docker/client/Dockerfile
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
  test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
  test/fixtures/org/omegat/core/TestCoreInitializer.java
Labels: build/release

#1221 docs: update javadoc of FindMatches class
  src/org/omegat/core/statistics/FindMatches.java
Labels: documentation

#1230 chore: update setup/teardown logic of acceptance test
  aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java
  build.gradle
  config/checkstyle/suppressions.xml
  test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
  test-acceptance/src/org/omegat/gui/editor/EditorUtilsGUITest.java
  test-acceptance/src/org/omegat/gui/main/TestCoreGUI.java
Labels: bug

#1227 feat: mark matches from source file translations as MATCH_SOURCE.FILES
  src/org/omegat/core/statistics/FindMatches.java
Labels: enhancement

#1108 feat: change the writable glossary by a right click
  src/org/omegat/Bundle.properties
  src/org/omegat/Bundle_zh_CN.properties
  src/org/omegat/gui/editor/EditorPopups.java
Labels: enhancement
