Repository omegat-org/omegat, pull requests merged in 2024-06, with the labels that each got.

#1047 [Bug#sf1258] http git repo erroneously set to svn
  src/org/omegat/core/team2/RemoteRepositoryFactory.java
  test/src/org/omegat/core/team2/RemoteRepositoryFactoryTest.java
Labels: bug

#1048 chore: Update release related tasks
  .github/workflows/gradle-build-master.yml
  build.gradle
  ci/azure-pipelines/build_steps.yml
  ci/azure-pipelines/check_steps.yml
  ci/gradle/gradle-scan.init.gradle
  ci/iscc
  ci/osslsigncode
  gradle/gradle-daemon-jvm.properties
  gradle/wrapper/gradle-wrapper.properties
  test-integration/docker/client/entrypoint.sh
Labels: build/release

#1056 Chore: Fix test-integration docker configuration
  compose.yml
  test-integration/docker/client/Dockerfile
Labels: build/release

#1059 refactor: add IMainWindow#resetDesktopLayout
  src/org/omegat/gui/main/ConsoleWindow.java
  src/org/omegat/gui/main/IMainWindow.java
  src/org/omegat/gui/main/MainWindow.java
  src/org/omegat/gui/main/MainWindowMenuHandler.java
  src/org/omegat/gui/preferences/view/AppearanceController.java
  test-acceptance/src/org/omegat/gui/main/TestMainWindow.java
  test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
  test/fixtures/org/omegat/core/TestCore.java
Labels: refactoring

#1061 chore: test-integ: fix spawn with Java 17
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
Labels: bug, build/release

#1062 refactor: reduce direct reference to real MainWindow object from MenuHandler
  src/org/omegat/gui/main/MainWindowMenuHandler.java
Labels: refactoring

#1064 chore(ci): bump bundle JRE@17.0.23+9
  ci/azure-pipelines/build_steps.yml
Labels: build/release

#1065 chore(ci): change build scripts
  azure-pipelines.yml
  ci/azure-pipelines/build_steps.yml
  ci/azure-pipelines/publish_release.yml
  ci/azure-pipelines/publish_weekly.yml
Labels: build/release

#1066 refactor: avoid usage of direct LT language class
  test/src/org/omegat/languagetools/LanguageToolTest.java
  test/src/org/omegat/languagetools/LuceneGosenCompatibilityTest.java
Labels: refactoring

#1068 refactor: Replace mainWindow obj access with Core.getMainWindow API
  src/org/omegat/gui/main/MainWindowMenuHandler.java
Labels: refactoring

#1067 refactor: Update EditorContoller to reference MainMenu fields
  src/org/omegat/gui/editor/EditorController.java
Labels: refactoring
