Repository omegat-org/omegat, pull requests merged in 2025-05, with the labels that each got.

#1323 refactor: EditorController: Replace java.util.logging with SLF4J based logging
  src/org/omegat/gui/editor/EditorController.java
Labels: refactoring

#1354 Refactor null-safe comparison method and replace usages
  config/checkstyle/suppressions.xml
  src/org/omegat/core/data/EntryKey.java
  src/org/omegat/util/StringUtil.java
  test/src/org/omegat/util/StringUtilTest.java
Labels: refactoring

#1364 fix: Set default and persist preferences for paragraph match from segmented tmx toggle
  src/org/omegat/gui/preferences/view/TMMatchesPreferencesController.java
Labels: bug

#1346 refactor: improve error logging
  src/org/omegat/Bundle.properties
  src/org/omegat/core/spellchecker/AbstractSpellChecker.java
Labels: refactoring

#1331 chore: Add morfologik-stemming jar and build-logic to build.gradle includes
  build.gradle
  language-modules/ast/build.gradle
  language-modules/ta/build.gradle
  language-modules/tl/build.gradle
Labels: build/release

#1328 Refactor translation search and remove unused field.
  src/org/omegat/core/Core.java
  src/org/omegat/gui/multtrans/MultipleTransFindThread.java
Labels: refactoring

#1385 error in output directory name
  build-logic/src/main/groovy/org.omegat.document-conventions.gradle
Labels: build/release, documentation

#1368 docs: contribution guide to add philosophy and about section
  src_docs/developer/0.AboutOmegaT.md
  src_docs/developer/07.PhilosophyAndPolicy.md
  src_docs/developer/index.md
Labels: documentation

#1369 docs: Expand localization guide for OmegaT contributors
  src_docs/developer/45.LocalizeApplicationAndManuals.md
Labels: documentation

#1356 docs: Add and refine developer contribution guidelines
  src_docs/developer/00.ContributingEcoSystem.md
  src_docs/developer/01.ContributingOmegaT.md
  src_docs/developer/03.GitWorkFlows.md
  src_docs/developer/07.MannerOfThePullRequest.md
  src_docs/developer/index.md
Labels: documentation

#1370 security: Vulnerabilities in the LanguageTool
  build.gradle
  gradle/libs.versions.toml
  language-modules/ar/build.gradle
  language-modules/ast/build.gradle
  language-modules/be/build.gradle
  language-modules/br/build.gradle
  language-modules/ca/build.gradle
  language-modules/da/build.gradle
  language-modules/de/build.gradle
  language-modules/el/build.gradle
  language-modules/en/build.gradle
  language-modules/eo/build.gradle
  language-modules/es/build.gradle
  language-modules/fa/build.gradle
  language-modules/fr/build.gradle
  language-modules/ga/build.gradle
  language-modules/gl/build.gradle
  language-modules/it/build.gradle
  language-modules/ja/build.gradle
  language-modules/km/build.gradle
  language-modules/nl/build.gradle
  language-modules/pl/build.gradle
  language-modules/pt/build.gradle
  language-modules/ro/build.gradle
  language-modules/ru/build.gradle
  language-modules/sk/build.gradle
  language-modules/sl/build.gradle
  language-modules/sv/build.gradle
  language-modules/ta/build.gradle
  language-modules/tl/build.gradle
  language-modules/uk/build.gradle
  language-modules/zh/build.gradle
Labels: bug

#1389 doc-devel: reorganize file numbering and fix a description of containerized tasks
  src_docs/developer/00.AboutOmegaT.md
  src_docs/developer/01.PhilosophyAndPolicy.md
  src_docs/developer/02.ContributingEcoSystem.md
  src_docs/developer/03.GuidelineForWelcomingBeginners.md
  src_docs/developer/04.ContributingOmegaT.md
  src_docs/developer/06.GitWorkFlows.md
  src_docs/developer/08.HowToBuild.md
  src_docs/developer/36.SourceTree.md
  src_docs/developer/45.LocalizeApplicationAndManuals.md
  src_docs/developer/index.md
  src_docs/mkdocs.yml
Labels: documentation

#1388 [6.0] chore: check for the existence of the menu invocation action method
  test/src/org/omegat/gui/main/MainWindowMenuTest.java
Labels: build/release

#1391 chore: Add PMD static code analysis with minimum rulesets
  .github/workflows/pmd-annotate.yml
  build-logic/src/main/groovy/org.omegat.java-conventions.gradle
  ci/github/problem-matcher.json
  config/pmd/ruleset.xml
  language-modules/br/src/test/java/org/omegat/languages/br/MorfologikTest.java
  language-modules/uk/src/main/java/org/omegat/languages/uk/UkrainianPlugin.java
  machinetranslators/apertium/src/main/java/org/omegat/machinetranslators/apertium/ApertiumTranslate.java
  machinetranslators/dummy/src/main/java/org/omegat/machinetranslators/dummy/Dummy.java
  spellchecker/hunspell/src/main/java/org/omegat/spellchecker/hunspell/HunSpellChecker.java
  spellchecker/hunspell/src/test/java/org/omegat/spellchecker/hunspell/HunspellSpellcheckerTest.java
  spellchecker/morfologik/src/main/java/org/omegat/spellchecker/morfologik/MorfologikSpellchecker.java
  src/org/omegat/core/segmentation/SRX.java
  src/org/omegat/core/team2/RemoteRepositoryProvider.java
  src/org/omegat/core/team2/impl/SVNAuthenticationManager.java
  src/org/omegat/core/team2/impl/SVNRemoteRepository2.java
  src/org/omegat/filters2/html2/FilterVisitor.java
  src/org/omegat/filters2/html2/HTMLFilter2.java
  src/org/omegat/filters3/xml/opendoc/OpenDocDialect.java
  src/org/omegat/filters3/xml/xliff/XLIFFDialect.java
  src/org/omegat/gui/accesstool/ProjectFileInformation.java
  src/org/omegat/gui/accesstool/ProjectFileRenderer.java
  src/org/omegat/gui/accesstool/QuickAccess.java
  src/org/omegat/gui/main/BaseMainWindowMenuHandler.java
  src/org/omegat/languagetools/LanguageClassBroker.java
  src/org/omegat/util/gui/CustomDockingUISettings.java
  src/org/omegat/util/gui/laf/WindowsDarkThemeDetector.java
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
  test/src/org/omegat/gui/editor/mark/MarkerTestBase.java
Labels: build/release, refactoring

#1379 update macOS signed/notarized builds information
  src_docs/developer/90.ReleaseProcedure.md
  src_docs/developer/92.CodeSigning.md
  src_docs/developer/93.BuildingInstallerPackage.md
Labels: build/release, documentation, mac

#1397 [6.0][java17] Add nashorn javascript engine
  build.gradle
  lib/licenses/Licenses.txt
Labels: java17, build/release, java21

#1399 [6.0][backport] improve test robustness against network reachability
  test/src/org/omegat/filters/TestFilterBase.java
  test/src/org/omegat/languagetools/LanguageToolTest.java
Labels: build/release, refactoring

#1402 [6.0] docs: Add Read the Docs configuration file
  .readthedocs.yml
Labels: build/release, documentation

#1393 Refactor editor mocks into reusable classes for tests
  test/fixtures/org/omegat/gui/editor/MockEditor.java
  test/fixtures/org/omegat/gui/editor/MockEditorSettings.java
  test/src/org/omegat/gui/editor/mark/MarkerTestBase.java
  test/src/org/omegat/gui/editor/mark/ReplaceMarkerTest.java
Labels: refactoring

#1407 Refactor OpenDocFilter for clarity and resource management
  src/org/omegat/filters3/xml/opendoc/OpenDocFilter.java
  test/src/org/omegat/filters/OpenDocFilterTest.java
Labels: refactoring

#1315 refactor: Color style enum name definition on ctor
  src/org/omegat/Bundle.properties
  src/org/omegat/util/gui/Styles.java
Labels: refactoring

#1409 chore: [6.0] Add GitHub Actions workflow to run gradle check
  .github/workflows/gradle-check-master.yml
  settings.gradle
Labels: build/release

#1406 fix: Enhance error handling for HTTP response exceptions
  src/org/omegat/Bundle.properties
  src/org/omegat/core/team2/IRemoteRepository2.java
  src/org/omegat/core/team2/impl/HTTPRemoteRepository.java
  test/src/org/omegat/core/team2/impl/HTTPRemoteRepositoryTest.java
Labels: bug

#1386 [6.0][backport]Fix the EventListener to check project status isLoaded to solve BUGS#1291.
  src/org/omegat/gui/properties/SegmentPropertiesArea.java
Labels: bug

#1363 docs: Update changes.txt
  release/changes.txt
Labels: documentation

#1297 Handle errors when loading project TMX files
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/ProjectTMX.java
  src/org/omegat/core/data/RealProject.java
  src/org/omegat/core/team2/TeamTool.java
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
  test-integration/src/org/omegat/core/data/TestTeamIntegrationChild.java
  test/src/org/omegat/core/data/AutoTmxTest.java
  test/src/org/omegat/core/data/TmxComplianceBase.java
  test/src/org/omegat/core/data/TmxComplianceTests.java
  test/src/org/omegat/core/data/TmxSegmentationTest.java
  test/src/org/omegat/core/statistics/FindMatchesTest.java
  test/src/org/omegat/gui/editor/mark/AltTranslationsMarkerTest.java
  test/src/org/omegat/gui/editor/mark/ComesFromAutoTMMarkerTest.java
  test/src/org/omegat/gui/editor/mark/ComesFromMTMarkerTest.java
Labels: refactoring

#1298 Remove unnecessary exception and handle filter loading errors
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/ProjectProperties.java
  src/org/omegat/gui/main/ProjectUICommands.java
Labels: bug, refactoring

#1317 refactor: use direct bundle key name instead of dynamic construction for better clarity with MainWindowStatusBar
  src/org/omegat/gui/editor/EditorTextArea3.java
  src/org/omegat/gui/main/MainWindowStatusBar.java
Labels: refactoring

#1403 [6.0] Add segmentation.conf validation tool
  src/org/omegat/core/segmentation/SRX.java
  src/org/omegat/core/segmentation/SegmentationConfValidator.java
  src/org/omegat/util/ValidationResult.java
  test/data/segmentation/locale_de_54/segmentation.conf
  test/data/segmentation/malformed0/segmentation.conf
  test/data/segmentation/malformed1/segmentation.conf
  test/src/org/omegat/core/segmentation/SegmentationConfValidatorTest.java
Labels: enhancement, security

#1418 feat(acceptance-test): wait search/matches panes ready and updated
  src/org/omegat/gui/dictionaries/DictionariesTextArea.java
  src/org/omegat/gui/glossary/GlossaryTextArea.java
  src/org/omegat/gui/matches/MatchesTextArea.java
  test-acceptance/data/project/glossary/glossary.txt
  test-acceptance/src/org/omegat/gui/editor/EditorUtilsGUITest.java
  test-acceptance/src/org/omegat/gui/glossary/GlossaryTextTest.java
  test-acceptance/src/org/omegat/gui/main/TestCoreGUI.java
  test-acceptance/src/org/omegat/gui/matches/MatchesTextTest.java
Labels: enhancement, build/release, refactoring

#1422 fix: team/HTTPRemoteRepository: handle HTTP_NOT_MODIFIED response correctly
  src/org/omegat/core/team2/impl/HTTPRemoteRepository.java
  test/src/org/omegat/core/team2/impl/HTTPRemoteRepositoryTest.java
Labels: bug, refactoring
