Repository omegat-org/omegat, pull requests merged in 2025-08, with the labels that each got.

#1581 refactor(tips): add `@Nullable` annotations and refine null checks for improved safety
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayModule.java
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayUtils.java
Labels: refactoring

#1586 test: add null checks for `window` in GUI tests to improve robustness
  test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
  test-acceptance/src/org/omegat/gui/dialogs/AboutDialogTest.java
  test-acceptance/src/org/omegat/gui/dialogs/ConflictDialogTest.java
  test-acceptance/src/org/omegat/gui/dialogs/ProjectPropertiesDialogTest.java
  test-acceptance/src/org/omegat/gui/editor/EditorTextAreaIntroTest.java
  test-acceptance/src/org/omegat/gui/editor/EditorTextLoadedTest.java
  test-acceptance/src/org/omegat/gui/editor/EditorUtilsGUITest.java
  test-acceptance/src/org/omegat/gui/glossary/GlossaryTextTest.java
  test-acceptance/src/org/omegat/gui/issues/IssuesPanelTest.java
  test-acceptance/src/org/omegat/gui/main/TestMainWindowMenuHandler.java
  test-acceptance/src/org/omegat/gui/matches/FuzzyMatchesSegmentsTest.java
  test-acceptance/src/org/omegat/gui/matches/MatchesTextExternalTmTest.java
  test-acceptance/src/org/omegat/gui/matches/MatchesTextTest.java
  test-acceptance/src/org/omegat/gui/properties/SegmentPropertiesAreaTest.java
Labels: refactoring

#1580 refactor(languagetools): enhance `LanguageToolNetworkBridge` stop logic and remove unused SpotBugs exclusions
  config/spotbugs/exclude.xml
  src/org/omegat/languagetools/LanguageToolNetworkBridge.java
Labels: refactoring

#1587 test(gui): extend timeout and add interruption handling in `ConflictDialogTest`
  test-acceptance/src/org/omegat/gui/dialogs/ConflictDialogTest.java
Labels: bug, UI

#1592 chore(checkstyle): add LineLength suppression for specific files
  config/checkstyle/suppressions.xml
Labels: refactoring

#1590 refactor(core): use diamond operator, add `@NotNull` annotations, and optimize map population in `SyncTMX`
  src/org/omegat/core/data/SyncTMX.java
Labels: refactoring

#1595 'licence' translation type
  src_docs/manual/ja/HowTo_TranslateOtherFiles.xml
Labels: documentation

#1600 fix(LT): always load LT English module
  src/org/omegat/languagetools/LanguageToolNativeBridge.java
Labels: bug

#1597 [6.0][BUGS#1302] XML filters does not handle DTD path with CJK characters properly
  release/changes.txt
  src/org/omegat/filters3/xml/XMLFilter.java
  test/data/xml/文件/test.dtd
  test/data/xml/文件/test.xml
  test/src/org/omegat/filters3/XMLFilterTest.java
Labels: bug

#1598 [BUGS#1302] XML filters does not handle DTD path with CJK characters properly
  src/org/omegat/filters3/xml/XMLFilter.java
  test/data/xml/文件/test.dtd
  test/data/xml/文件/test.xml
  test/src/org/omegat/filters3/XMLFilterTest.java
Labels: bug

#1599 doc: update changes.txt
  release/changes.txt
Labels: documentation

#1602 [6.0][BUGS#1293] chore: Bump dependencies to avoid vulnerability
  build.gradle
  release/changes.txt
  src/org/omegat/filters2/po/PoFilter.java
  src/org/omegat/util/MagicComment.java
  src/org/omegat/util/TMXReader2.java
Labels: refactoring, dependencies

#1605 [6.0] chore(test-integ/container): update Dockerfile and configurations
  .docker-compose.yml
  compose.yml
  test-integration/docker/client/Dockerfile
  test-integration/docker/client/entrypoint.sh
  test-integration/docker/client/gitconfig
  test-integration/runner.sh
Labels: build/release

#1606 chore(test-integ/container): Enforce operations in UTF-8
  test-integration/docker/client/Dockerfile
  test-integration/docker/client/entrypoint.sh
Labels: build/release

#1619 chore(docs): add class-level Javadoc for readability and maintainability
  machinetranslators/apertium/src/main/java/org/omegat/machinetranslators/apertium/ApertiumTranslate.java
  machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/AbstractMyMemoryTranslate.java
  machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryHumanTranslate.java
  machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryMachineTranslate.java
  machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryTranslate.java
  src/org/omegat/util/gui/DataTableStyling.java
  src/org/omegat/util/gui/DragTargetOverlay.java
  theme/src/main/java/org/omegat/gui/theme/DefaultFlatDarkTheme.java
  theme/src/main/java/org/omegat/gui/theme/DefaultFlatLightTheme.java
Labels: refactoring, documentation

#1620 style: improve formatting, add checks, and update suppressions
  config/checkstyle/suppressions.xml
  src/org/omegat/gui/matches/MatchesVarExpansion.java
  src/org/omegat/util/CredentialsManager.java
  src/org/omegat/util/OConsts.java
  src/org/omegat/util/Preferences.java
  src/org/omegat/util/gui/FontFallbackListener.java
  src/org/omegat/util/gui/ViewFactoryHelper.java
Labels: refactoring

#1631 chore(dependencies): update library versions and refine test configurations
  build.gradle
  gradle/libs.versions.toml
Labels: build/release, dependencies

#1624 refactor(ui/plugin): enhance plugin management and table views
  build-logic/src/main/groovy/org.omegat.module-conventions.gradle
  config/checkstyle/suppressions.xml
  src/org/omegat/Bundle.properties
  src/org/omegat/core/data/PluginInformation.java
  src/org/omegat/filters2/master/PluginUtils.java
  src/org/omegat/gui/preferences/view/PluginDetailsPane.java
  src/org/omegat/gui/preferences/view/PluginInfoTableModel.java
  src/org/omegat/gui/preferences/view/PluginsPreferencesController.java
  src/org/omegat/gui/preferences/view/PluginsPreferencesPanel.form
  src/org/omegat/gui/preferences/view/PluginsPreferencesPanel.java
  src/org/omegat/util/PluginInstaller.java
Labels: enhancement, refactoring, UI

#1618 fix(pofilter): support multi-line msgctxt
  src/org/omegat/filters2/po/PoFilter.java
  src/org/omegat/gui/comments/CommentsTextArea.java
  src/org/omegat/util/StringUtil.java
  test/data/filters/po/file-POFilter-multilines.po
  test/src/org/omegat/filters/POFilterTest.java
Labels: bug, refactoring
