Repository omegat-org/omegat, pull requests merged in 2025-06, with the labels that each got.

#1341 fix: StringUtils: bugs in edge cases and enhance unit test cases
  src/org/omegat/util/StringUtil.java
  test/src/org/omegat/util/StringUtilTest.java
Labels: bug, refactoring

#1433 fix: correct typo and refactor normalizeWidth processing logic
  src/org/omegat/util/StringUtil.java
  test/src/org/omegat/util/StringUtilTest.java
Labels: bug, refactoring, documentation

#1437 refactor(core): remove Hungarian notation from field names in `Searcher` and `SearchResultEntry` class
  config/checkstyle/suppressions.xml
  src/org/omegat/core/search/SearchResultEntry.java
  src/org/omegat/core/search/Searcher.java
Labels: refactoring

#1431 Refactor(core): Decrease Searcher complexity and add functional and unit tests
  config/checkstyle/suppressions.xml
  src/org/omegat/core/search/Searcher.java
  src/org/omegat/util/StringUtil.java
  test/src/org/omegat/core/search/SearcherTest.java
  test/src/org/omegat/util/StringUtilTest.java
Labels: refactoring

#1387 the 'latest' suffix is not used anymore
  src/org/omegat/help/Help.java
Labels: bug, documentation

#1442 feat(util): add debug-level logging methods to Log class
  src/org/omegat/util/Log.java
Labels: enhancement

#1443 fix(tests): handle directory creation failure in `TestTeamIntegration#setupRunnerDirectory`
  test-integration/src/org/omegat/core/data/TestTeamIntegration.java
Labels: bug

#1452 fix(filters3): avoid uninitialized read of field `encoding` in XMLReader
  src/org/omegat/filters3/xml/XMLReader.java
Labels: bug

#1460 test(acceptance): Project Properties dialog handling
  build-logic/src/main/groovy/org.omegat.verification-conventions.gradle
  src/org/omegat/gui/dialogs/ProjectPropertiesDialog.java
  src/org/omegat/gui/dialogs/ProjectPropertiesDialogController.java
  src/org/omegat/gui/main/BaseMainWindowMenu.java
  src/org/omegat/gui/main/ProjectUICommands.java
  test-acceptance/src/org/omegat/gui/align/AlignerWindowTest.java
  test-acceptance/src/org/omegat/gui/dialogs/ProjectPropertiesDialogTest.java
  test-acceptance/src/org/omegat/gui/main/TestMainWindowMenuHandler.java
Labels: bug, build/release, refactoring, UI

#1462 docs: update developer documentation and add git repository analysis
  .mailmap
  ci/git-code-analysis.sh
  src_docs/developer/91.appendix.md
  src_docs/developer/94.GitRepositoryAnalysis.md
  src_docs/developer/index.md
Labels: documentation

#1459 Match origin string improvement
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/matches/MatchesVarExpansion.java
Labels: UI

#1457 refactor(git): replace keySet iteration with entrySet in `GITRemoteRepository2`
  src/org/omegat/core/team2/impl/GITRemoteRepository2.java
Labels: refactoring

#1458 refactor(xliff): modularize target element generation logic in `Xliff1Filter`
  src/org/omegat/filters4/xml/xliff/Xliff1Filter.java
Labels: refactoring

#1468 fix(gui): remove duplicated null check and improve comments in `Edito…
  src/org/omegat/gui/editor/EditorController.java
Labels: refactoring

#1473 refactor(gui): modularize last changes text loading and clean up `LastChangesDialog` initialization
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/dialogs/LastChangesDialog.java
Labels: refactoring

#1470 refactor(core): update visibility of statistics headers in `StatsResult`
  src/org/omegat/core/statistics/StatsResult.java
Labels: refactoring

#1471 refactor(gui): move date and time format initialization to `ModificationInfoVarExpansion` constructor
  src/org/omegat/gui/editor/ModificationInfoManager.java
Labels: refactoring

#1453 refactor(xml): replace String-based encoding with `Charset` and improve EOL detection in `XMLReader`
  src/org/omegat/filters3/xml/XMLFilter.java
  src/org/omegat/filters3/xml/XMLReader.java
Labels: refactoring

#1479 refactor(scripting): unify logging methods and improve exception handling
  src/org/omegat/gui/scripting/ScriptingWindow.java
  src/org/omegat/util/Log.java
Labels: refactoring

#1480 fix(threading): mark `start` field as `volatile` in `ScriptWorker`
  src/org/omegat/gui/scripting/ScriptingWindow.java
Labels: bug

#1326 refactor: Refactor TestCore and add EditorControllerTest.
  src/org/omegat/core/Core.java
  src/org/omegat/gui/editor/EditorTextArea3.java
  test/fixtures/org/omegat/core/TestCore.java
  test/fixtures/org/omegat/core/TestCoreInitializer.java
  test/src/org/omegat/gui/editor/EditorControllerTest.java
Labels: refactoring

#1489 refactor(gui): add `instanceof` check for safer casting in cell renderers
  src/org/omegat/gui/properties/MultilineCellRenderer.java
  src/org/omegat/gui/properties/SingleLineCellRenderer.java
Labels: refactoring

#1487 refactor(tokenizer): implement `equals` and `hashCode` in `TagJoiningFilter` for better object comparison
  src/org/omegat/tokenizer/LuceneJapaneseTokenizer.java
Labels: refactoring

#1484 refactor(gui): extract `SideShapeSpec` class and factory method to simplify border rendering logic
  src/org/omegat/util/gui/RoundedCornerBorder.java
Labels: refactoring

#1483 refactor(logging): enhance directory creation error handling and cleanup logic
  src/org/omegat/util/logging/OmegaTFileHandler.java
  test-integration/src/org/omegat/util/logging/TestLogFileHandler.java
Labels: refactoring

#1491 refactor(tests): inject `FilterMaster` dependency and remove redundant setup
  test/src/org/omegat/core/statistics/CalcMatchStatisticsTest.java
Labels: bug

#1490 refactor(gui): extract `IssuesColumn`, `IssuesTableModel`, and `IssuesTypeListModel` into separate classes
  src/org/omegat/gui/issues/IssueColumn.java
  src/org/omegat/gui/issues/IssuesPanelController.java
  src/org/omegat/gui/issues/IssuesTableModel.java
  src/org/omegat/gui/issues/IssuesTypeListModel.java
  test-acceptance/src/org/omegat/gui/issues/IssuesPanelTest.java
Labels: refactoring

#1481 refactor(html2): improve constructor logic in `FilterVisitor`
  src/org/omegat/filters2/html2/FilterVisitor.java
Labels: refactoring

#1053 feat: Optionally allow selecting segment with a single click
  src/org/omegat/Bundle.properties
  src/org/omegat/gui/editor/EditorController.java
  src/org/omegat/gui/editor/EditorTextArea3.java
  src/org/omegat/gui/editor/IEditor.java
  src/org/omegat/gui/preferences/view/EditingBehaviorController.java
  src/org/omegat/gui/preferences/view/EditingBehaviorPanel.form
  src/org/omegat/gui/preferences/view/EditingBehaviorPanel.java
  src/org/omegat/util/Preferences.java
  src_docs/manual/en/OmegaT_Preferences.xml
  test-acceptance/src/org/omegat/gui/editor/EditorTextAreaIntroTest.java
  test-acceptance/src/org/omegat/gui/editor/EditorTextLoadedTest.java
  test/data/preferences/omegat.prefs.xml
Labels: enhancement

#1493 chore(build): update publishing plugins and migrate repository configs to Nexus
  build-logic/src/main/groovy/org.omegat.module-conventions.gradle
  build-logic/src/main/groovy/org.omegat.publish-conventions.gradle
  build-logic/src/main/groovy/org.omegat.version-conventions.gradle
  build.gradle
Labels: build/release

#1504 refactor(filters): improve JavaDoc in `AbstractFilter` for enhanced readability
  src/org/omegat/filters2/AbstractFilter.java
Labels: documentation

#1506 refactor(config): remove obsolete configuration conversion classes
  src/org/omegat/Main.java
  src/org/omegat/convert/ConvertConfigs.java
  src/org/omegat/convert/ConvertTo213.java
  src/org/omegat/convert/v20to21/Convert20to21.java
  src/org/omegat/convert/v20to21/data/Filters.java
  src/org/omegat/convert/v20to21/data/HTMLOptions.java
  src/org/omegat/convert/v20to21/data/Instance.java
  src/org/omegat/convert/v20to21/data/OneFilter.java
  src/org/omegat/convert/v20to21/data/OpenDocOptions.java
  src/org/omegat/convert/v20to21/data/OpenXMLOptions.java
  src/org/omegat/convert/v20to21/data/TextOptions.java
  src/org/omegat/convert/v20to21/data/XHTMLOptions.java
Labels: refactoring

#1482 refactor(core): unify `OSXEventListener` and `IOpenFilesHandler` into single class
  src/org/omegat/util/gui/OSXIntegration.java
Labels: bug, refactoring, mac

#1472 fix(filters4/xliff1): fix the anti-pattern that catch the null pointer exception and refactor complex switch-case blocks
  src/org/omegat/filters4/xml/xliff/Xliff1Filter.java
Labels: refactoring

#1510 docs(adr): add decision record for comprehensive static code analysis strategy (#2025003)
  src_docs/developer/adr/2025003.StaticCodeAnalysis.md
  src_docs/developer/adr/index.md
  src_docs/developer/stylesheets/extra.css
  src_docs/mkdocs.yml
  src_docs/requirements.txt
Labels: documentation

#1518 refactor(spellchecker): add `@Nullable` annotations and improve null check
  src/org/omegat/core/spellchecker/AbstractSpellChecker.java
  src/org/omegat/core/spellchecker/ISpellCheckerDictionary.java
  src/org/omegat/core/spellchecker/SpellCheckerMarker.java
Labels: refactoring

#1516 refactor(module): add nullability annotations and improve null handling across machine translation classes
  config/checkstyle/suppressions.xml
  machinetranslators/belazar/build.gradle
  machinetranslators/belazar/src/main/java/org/omegat/machinetranslators/belazar/BelazarTranslate.java
  machinetranslators/google/build.gradle
  machinetranslators/google/src/main/java/org/omegat/machinetranslators/google/Google2Translate.java
  machinetranslators/ibmwatson/build.gradle
  machinetranslators/ibmwatson/src/main/java/org/omegat/machinetranslators/ibmwatson/IBMWatsonTranslate.java
  machinetranslators/mymemory/build.gradle
  machinetranslators/mymemory/src/main/java/org/omegat/machinetranslators/mymemory/MyMemoryMachineTranslate.java
  machinetranslators/yandex/build.gradle
  machinetranslators/yandex/src/main/java/org/omegat/machinetranslators/yandex/YandexCloudTranslate.java
  src/org/omegat/core/machinetranslators/BaseCachedTranslate.java
Labels: bug, refactoring

#1517 refactor(tips): add nullability annotations and include `jetbrains.annotations` dependency for improved type safety
  tipoftheday/build.gradle
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayModule.java
  tipoftheday/src/main/java/org/omegat/gui/tipoftheday/TipOfTheDayUtils.java
Labels: bug, refactoring

#1514 refactor(aligner): add nullability annotations and improve safety checks across aligner classes
  aligner/build.gradle
  aligner/src/main/java/org/omegat/gui/align/AlignFilePickerController.java
  aligner/src/main/java/org/omegat/gui/align/AlignPanelController.java
  aligner/src/main/java/org/omegat/gui/align/Aligner.java
  aligner/src/main/java/org/omegat/gui/align/AlignerModule.java
  aligner/src/main/resources/org/omegat/gui/align/Bundle.properties
Labels: bug, refactoring

#1049 feat: update tmx writer, escaper, and unit test
  src/org/omegat/util/TMXWriter2.java
  src/org/omegat/util/TmxEscapingWriterFactory.java
  test/data/tmx/test-save-tmx14.tmx
  test/src/org/omegat/util/TMXWriterTest.java
  test/src/org/omegat/util/TmxEscapingWriterTest.java
Labels: enhancement

#1505 refactor(filters): extract `isTranslateAttribute` method to simplify `FilterVisitor` logic
  src/org/omegat/filters2/html2/FilterVisitor.java
Labels: refactoring, documentation

#1523 chore: update CODEOWNERS with granular ownership rules for project files
  .github/CODEOWNERS
Labels: build/release

#1520 refactor(core): add `@Nullable` annotations to improve null-safety and clarify method contracts across multiple classes
  src/org/omegat/core/data/ParseEntry.java
  src/org/omegat/core/data/ProtectedPart.java
  src/org/omegat/core/data/SourceTextEntry.java
  src/org/omegat/core/segmentation/Segmenter.java
  src/org/omegat/gui/editor/mark/Mark.java
  src/org/omegat/gui/segmentation/SegmentationCustomizer.java
  src/org/omegat/help/Help.java
  src/org/omegat/util/StringUtil.java
  src/org/omegat/util/TMXWriter2.java
Labels: bug, refactoring

#1469 feat(core/classloaders): use individual class loader for each plugin types
  src/org/omegat/Main.java
  src/org/omegat/core/spellchecker/SpellCheckerManager.java
  src/org/omegat/filters2/master/PluginUtils.java
  src/org/omegat/languagetools/LanguageClassBroker.java
  test-acceptance/src/org/omegat/TestMainInitializer.java
Labels: enhancement, refactoring

#1528 test: enhance ProjectPropertiesDialogTest with additional validations for UI elements
  test-acceptance/src/org/omegat/gui/dialogs/ProjectPropertiesDialogTest.java
Labels: bug, build/release

#1215 [BUGS#1251][6.0][backport] fix: FindMatches#search ignore penalty when segmented matches
  release/changes.txt
  src/org/omegat/core/data/ProjectTMX.java
  src/org/omegat/core/matching/NearString.java
  src/org/omegat/core/statistics/FindMatches.java
  test/data/tmx/penalty-010/segment_1.tmx
  test/data/tmx/test-multiple-entries.tmx
  test/src/org/omegat/core/statistics/FindMatchesTest.java
Labels: bug

#1365 [6.0][BUGS#1279]fix: glossary sorting and issue handling logic
  src/org/omegat/gui/glossary/GlossarySearcher.java
  src/org/omegat/gui/issues/IssuesPanelController.java
  test/src/org/omegat/gui/glossary/FindGlossaryThreadTest.java
Labels: bug, refactoring
