Repository omegat-org/omegat, pull requests merged in 2025-02, with the labels that each got.

#1258 chore: support package build on windows 11 on aarch64
  build.gradle
  docs_devel/docs/93.BuildingInstallerPackage.md
Labels: build/release

#1260 fix: windows package build permission issue
  build.gradle
  ci/iscc
  ci/iscc-entrypoint.sh
Labels: build/release

#1267 Change label for "break/exception" checkbox
  doc_src/en/App_Segmentation.xml
  doc_src/en/OmegaT_Preferences.xml
  release/changes.txt
  src/org/omegat/Bundle.properties
Labels: enhancement, documentation, UI

#1263 fix pt-br UI issues
  release/changes.txt
  src/org/omegat/Bundle_pt_BR.properties
Labels: bug, L10N/Translation, UI

#1271 Add direct links to items in the HTML manual
  doc_src/en/App_ApplicationFolder.xml
  doc_src/en/App_Bidi.xml
  doc_src/en/App_ConfigurationFolder.xml
  doc_src/en/App_FileFilters.xml
  doc_src/en/App_Glossaries.xml
  doc_src/en/App_PostProcessingCommands.xml
  doc_src/en/App_Regex.xml
  doc_src/en/App_Segmentation.xml
  doc_src/en/App_ShortCuts.xml
  doc_src/en/Dialogs_ProjectProperties.xml
  doc_src/en/HowTo_Install.xml
  doc_src/en/HowTo_RestoreYourData.xml
  doc_src/en/HowTo_Run.xml
  doc_src/en/HowTo_SetUpTeamProject.xml
  doc_src/en/HowTo_TranslateOtherFiles.xml
  doc_src/en/HowTo_UseTM.xml
  doc_src/en/HowTo_UseTeamProject.xml
  doc_src/en/Introduction.xml
  doc_src/en/Menus_Edit.xml
  doc_src/en/Menus_GoTo.xml
  doc_src/en/Menus_Help.xml
  doc_src/en/Menus_Options.xml
  doc_src/en/Menus_Project.xml
  doc_src/en/Menus_Tools.xml
  doc_src/en/Menus_View.xml
  doc_src/en/OmegaT_Appendices.xml
  doc_src/en/OmegaT_EditorsPanes.xml
  doc_src/en/OmegaT_HowTo.xml
  doc_src/en/OmegaT_Menus.xml
  doc_src/en/OmegaT_Preferences.xml
  doc_src/en/OmegaT_ProjectFolder.xml
  doc_src/en/OmegaT_WindowsAndDialogs.xml
  doc_src/en/Windows_Aligner.xml
  doc_src/en/Windows_Scripts.xml
  doc_src/en/Windows_SourceFilesList.xml
  doc_src/en/Windows_TextReplace.xml
  doc_src/en/Windows_TextSearch.xml
Labels: enhancement, documentation

#1259 chore: use custom launch4j binaries
  build.gradle
Labels: build/release

#1266 Various documentation fixes and additions
  doc_src/en/App_ConfigurationFolder.xml
  doc_src/en/Dialogs_ProjectProperties.xml
  doc_src/en/HowTo_SetUpTeamProject.xml
  doc_src/en/HowTo_UseTeamProject.xml
  doc_src/en/Introduction.xml
  doc_src/en/OmegaT_EditorsPanes.xml
  doc_src/en/OmegaT_Preferences.xml
  doc_src/en/OmegaT_ProjectFolder.xml
  release/changes.txt
Labels: enhancement, documentation

#1220 feat: introduce matchSource match template variable
  config/checkstyle/suppressions.xml
  src/org/omegat/Bundle.properties
  src/org/omegat/core/matching/NearString.java
  src/org/omegat/core/statistics/FindMatches.java
  src/org/omegat/gui/matches/MatchesVarExpansion.java
  test-acceptance/src/org/omegat/gui/matches/MatchesTextAreaTest.java
  test/src/org/omegat/gui/matches/MatchesVarExpansionTest.java
Labels: enhancement

#1195 fix: passing filter context
  src/org/omegat/filters2/hhc/HHCFilter2.java
  src/org/omegat/filters2/hhc/HHCFilterVisitor.java
  src/org/omegat/filters2/html2/FilterVisitor.java
  src/org/omegat/filters2/html2/HTMLFilter2.java
Labels: refactoring
